- name: ensure nginx folders exist
  file: 
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/nginx
    - /etc/nginx/sites-enabled

- name: deploy nginx.conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  loop:
    - src: nginx.conf
      dest: /etc/nginx/nginx.conf
    - src: sites-enabled-default
      dest: /etc/nginx/sites-enabled/default

