#!/bin/bash

set -eEux

# Run Tests
./gradlew --parallel test

# Generate reports
./gradlew --parallel jacocoTestReport

# upload coverage report - https://github.com/codecov/example-gradle
bash <(curl -s https://codecov.io/bash)

