#!/bin/bash

set -eEux

# Run Tests
./gradlew -x :smoke-testing:test -parallel test jacocoTestReport


# upload coverage report - https://github.com/codecov/example-gradle
bash <(curl -s https://codecov.io/bash)

