#!/bin/bash

set -ux

export CC_TEST_REPORTER_ID="$CODE_CLIMATE_TEST_COVERAGE_ID"

curl -L \
  https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 \
  > ./cc-test-reporter

chmod +x ./cc-test-reporter

./cc-test-reporter before-build

./gradlew -x :smoke-testing:test -parallel test jacocoTestReport

result="$?"

./cc-test-reporter after-build --exit-code "$result"

if [ "$result" = 0 ]; then
  # upload coverage report - https://github.com/codecov/example-gradle
  bash <(curl -s https://codecov.io/bash)
fi

exit "$result"
