- name: create service user to run flyway
  become: true
  user:
    name: "{{ flyway_user }}"
    create_home: yes
    system: yes

- name: Download flyway CLI
  become: true
  become_user: flyway
  get_url:
    url: "{{ flyway_download_location }}"
    dest: "{{ flyway_downloaded_file_location }}"
    mode: "644"
    checksum: "md5:57f496acc6399fe30ee1fd957545abf1"

- name: extract flyway
  become: true
  become_user: flyway
  unarchive:
    copy: no
    src: "{{ flyway_downloaded_file_location }}"
    dest: "/home/flyway/"
    creates: "{{ flyway_extracted_location }}"

- name: deploy flyway conf file
  become: true
  become_user: flyway
  template:
    src: flyway.conf.j2
    dest: "{{ flyway_extracted_location }}/conf/flyway.conf"
    mode: "644"

- name: extract migrations
  become: true
  become_user: flyway
  unarchive:
     src: migrations.zip
     dest: "{{ flyway_extracted_location }}/sql/"
     mode: "644"

- name: run flyway
  become: true
  become_user: flyway
  command: "{{ flyway_extracted_location }}/flyway migrate"
  register: flyway
  changed_when: '"is up to date. No migration necessary" not in flyway.stdout'
