# Number of days of inactivity before an issue becomes stale
# Chosen to be relatively large so that a stale issue is
# very likely actually stale and really not moving forward.
daysUntilStale: 180

# Number of days of inactivity before a stale issue is closed
# Close date is chosen to be large so that we rarely
# close issues due to staleness.
daysUntilClose: 1800

# Issues with these labels will never be considered stale
exemptLabels:
  
# Label to use when marking an issue as stale
staleLabel: 'Stale'

markComment: >
  I noticed there has not been much activity on this issue.
  Please check this issue and close it if it no longer applies.

  Otherwise to help move this issue move forward, please add a
  comment summarizing any further actions that need to be taken
  in order to resolve this issue.

closeComment: false
only: issues

