# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - "Problem in Release"
  - "Problem in Pre-Release "
# Label to use when marking an issue as stale
staleLabel: 'Stale'

markComment: >
  This issue has been automatically marked as stale because it has not
  had recent activity. If there is something that can be done to resolve
  this issue, please add a comment indicating what that would be and this issue will
  be re-opened. If there are multiple items that can be completed independently,
  we encourage you to use the "reference in new issue" option next to any
  outstanding comment so that we may divide and conquer.

closeComment: false

pulls:
   daysUntilStale: 14
   markComment: >
     This pull request has been automatically marked as stale because it has not had
     recent activity. We are eager to see this work completed, please update and
     re-open as soon as possible.

