# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90 
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1 
# Issues with these labels will never be considered stale
exemptLabels:
  - "Problem"
  - "Pre-Release Problem"
# Label to use when marking an issue as stale
staleLabel: 'Stale'

markComment: >
  The TripleA team regrets this issue was not solved sooner. To keep focus
  on latest issues and the most pressing tasks, 
  this issue has been automatically marked as stale because it has not 
  had recent activity.  If the issue may be closed, please do so. 
  If there are remaining items, we encourage for those items to be 
  resubmitted as new, independent, concise tasks. The strategy
  is divide and conquer. Thank you for your contributions.

closeComment: false

pulls:
   daysUntilStale: 14 
   markComment: >
     This pull request has been automatically marked as stale because it has not had
     recent activity. We are eager to see this work completed, please update and
     re-open as soon as possible.

