language: java
jdk:
- oraclejdk8
install: true
script:
- gradle test
before_deploy:
- wget -O setup https://github.com/triplea-game/triplea/blob/master/.travis/setup?raw=true
- chmod +x setup && ./setup
- export TAGGED_VERSION="$BUILD_VERSION.$TRAVIS_BUILD_NUMBER"
- gradle release
- wget -O push_tag https://github.com/triplea-game/triplea/blob/master/.travis/push_tag?raw=true
- chmod +x push_tag && ./push_tag
deploy:
  provider: releases
  api_key:
    secure: nxaqYrkXLGL3W20/eCnf63DLjMrQAhEuW44jggh1/nI383goa+u6w0bBtWCxRdVzos7t4dpVfS6+kv6oIHacm9zVA+RYrqy5opzCJhq8lmXVVRijbALzUeiFif2HURMaKWj0ynRNVlAyBHzazPTLZVWywifpdSubSkuMWkl20cmuKu/Hg3c1EC9se3OYhhTHx3Hya7xSrctrDEYLsEBAUZzkKfscqRVqwwltS88CgIMtRISDpSBGrtH0t1uAH6NitTSguGgb+QEpqnELcRLymX2G1yzMA4Xr5c/L34MfbBKf8vIuG9t411xYuLoyKoUbroTWxSnPwlSy6PHz+QJ7UCXbDkATOGO3chxlKxglppvI/G3n2YP5Zf2dAaDlHblpvarh55i/4i4sKB2AbvvzkIHrQJwUgmLCbpN8/Vp9GWcGkd6i5U7F8tNInCs6ttX3oGvGOfYEXs02Ctyiea4LAqk4S7GZTuV2QXqxXglL4eRIwZ4UETiwgoAAtHma63Eq7+9t2ykMlk7zAK96FGwJrB97wa08aPuSxL94IYEBmn9Ht/vKXRiNQMvpnfp4rWQtL3cqbVyYAg5EjKb4PsBmnb91+RXtnWFOY1RpZGt8sPXYd+KZYzN1BXTFJEpaLLsIDN6r7nMcAvJDUmucaM+m7giPXz1ZBGAic3UBM1qMCgI=
  ## This is the list of files to be deployed to github releases
  file:
    - build/libs/triplea-${TAGGED_VERSION}-all.jar
    - build/releases/triplea_windows-x64_${TAGGED_VERSION}.exe
    - build/releases/triplea_windows_${TAGGED_VERSION}.exe
    - build/releases/triplea_macos_${TAGGED_VERSION}.dmg
    - build/releases/triplea_unix_${TAGGED_VERSION}.sh
    - build/distributions/triplea-${TAGGED_VERSION}-all_platforms.zip
    - build/distributions/triplea-${TAGGED_VERSION}-bots.zip
    - build/distributions/triplea-${TAGGED_VERSION}-server.zip
  skip_cleanup: true
  prerelease: true
  on:
    repo: triplea-game/triplea
    tags: false
    branches:
      only:
        - master
