dist: xenial
sudo: false
language: java
matrix:
  include:
  - jdk: openjdk11
    env: TRIPLEA_RELEASE=true
  - jdk: openjdk12
    env: TRIPLEA_RELEASE=false
addons:
  postgresql: "10"
  apt:
    packages:
      # python for map file splitter
      - python3
      - python3-yaml
install:
 - echo "create database lobby_db" | psql -h localhost -U postgres -d postgres
 - echo "create user lobby_user with password 'postgres'" | psql -h localhost -U postgres -d postgres
 - echo "alter database lobby_db owner to lobby_user" | psql -h localhost -U postgres -d postgres
 - sed -i "s/.0$/.$TRAVIS_BUILD_NUMBER/" game-core/src/main/resources/META-INF/triplea/product.properties
 - RELEASE_VERSION=$(sed 's/version\s*=\s*//' game-core/src/main/resources/META-INF/triplea/product.properties)
 - ./gradlew flywayMigrate
 - ./gradlew shadowJar
 # Http server needs to be launched to supprt integ testing. Launching it here allows output from the server to go to the travis log.
 - "java -jar http-server/build/libs/triplea-http-server-${RELEASE_VERSION}.jar server ./http-server/configuration-prerelease.yml &"
before_script:
- ./.travis/setup_gpg
script:
- ./gradlew --parallel check jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)  # upload coverage report - https://github.com/codecov/example-gradle
before_deploy:
- INSTALL4J_HOME=~/install4j
- ./.travis/install_install4j "$INSTALL4J_HOME"
- (./gradlew -Pinstall4jHomeDir="$INSTALL4J_HOME" release  2> errors && echo "INSTALL4J finished with $(wc -l errors)") || (echo "INSTALL4J FAILED" && tail -500 errors)
- ./.travis/collect_artifacts
- ./.travis/generate_artifact_checksums
- ./.travis/push_tag
## Live update maps list on website, read the maps in 'triplea_maps.yaml' and commit updated data files
## to website json data directory.
- ./.travis/push_maps
deploy:
  provider: releases
  api_key:
    secure: nxaqYrkXLGL3W20/eCnf63DLjMrQAhEuW44jggh1/nI383goa+u6w0bBtWCxRdVzos7t4dpVfS6+kv6oIHacm9zVA+RYrqy5opzCJhq8lmXVVRijbALzUeiFif2HURMaKWj0ynRNVlAyBHzazPTLZVWywifpdSubSkuMWkl20cmuKu/Hg3c1EC9se3OYhhTHx3Hya7xSrctrDEYLsEBAUZzkKfscqRVqwwltS88CgIMtRISDpSBGrtH0t1uAH6NitTSguGgb+QEpqnELcRLymX2G1yzMA4Xr5c/L34MfbBKf8vIuG9t411xYuLoyKoUbroTWxSnPwlSy6PHz+QJ7UCXbDkATOGO3chxlKxglppvI/G3n2YP5Zf2dAaDlHblpvarh55i/4i4sKB2AbvvzkIHrQJwUgmLCbpN8/Vp9GWcGkd6i5U7F8tNInCs6ttX3oGvGOfYEXs02Ctyiea4LAqk4S7GZTuV2QXqxXglL4eRIwZ4UETiwgoAAtHma63Eq7+9t2ykMlk7zAK96FGwJrB97wa08aPuSxL94IYEBmn9Ht/vKXRiNQMvpnfp4rWQtL3cqbVyYAg5EjKb4PsBmnb91+RXtnWFOY1RpZGt8sPXYd+KZYzN1BXTFJEpaLLsIDN6r7nMcAvJDUmucaM+m7giPXz1ZBGAic3UBM1qMCgI=
  file_glob: true
  file: build/artifacts/*
  ## This is set to true to not delete artifacts between the 'before-deploy' and 'deploy' steps
  skip_cleanup: true
  prerelease: true
  on:
    tags: false
    condition: "$TRIPLEA_RELEASE = true"
    repo: triplea-game/triplea
    branch: master
