language: java
jdk:
- oraclejdk8
install: true
script:
- gradle test
before_deploy:
- export TAGGED_VERSION="$BUILD_VERSION.$TRAVIS_BUILD_NUMBER"

- echo "Downloading and installing install4j"
- wget -O install4j_unix.sh http://github.com/triplea-game/assets/blob/master/install4j/install4j_unix_6_0_4.sh?raw=true
- chmod +x install4j_unix.sh
- ./install4j_unix.sh -q

- echo "Now downloading OS specific JRE bundles to be included as needed by install4j"
- wget -O jre-8u66-macosx-x64.tar.gz http://github.com/triplea-game/assets/blob/master/install4j/jre-8u66-macosx-x64.tar.gz?raw=true
- mv jre-8u66-macosx-x64.tar.gz ~/install4j6/jres/
- wget -O jre-8u66-windows-x86.tar.gz http://github.com/triplea-game/assets/blob/master/install4j/jre-8u66-windows-x64.tar.gz?raw=true
- mv jre-8u66-windows-x86.tar.gz ~/install4j6/jres/

- echo "Setup environment for execution of install4j through gradle"
- mkdir -p ~/.gradle
## Next, append install4jHomeDir property to ~/.gradle/gradle.properties, iff the property is not already present in the file
## The grep simply does the check if the property is there, the echo then does the append, the CD subshell gets us the absolute path to the home folder,
## and last this is appended to the gradle properties file
- grep -q "install4jHomeDir" ~/.gradle/gradle.properties 2> /dev/null || echo "install4jHomeDir=$(cd ~ && pwd)/install4j6" >> ~/.gradle/gradle.properties

## Register license with the install4j binary
- ~/install4j6/bin/install4jc -L $INSTALL4J_LICENSE

- echo "Building release artifacts"
- gradle release

- echo "Configure Git and PUSH A TAG - this trigger and execute the deploy section of this same build file, in the same travis linux container (skip_cleanup setting below is important)"
- git config --global user.email "tripleabuilderbot@gmail.com"
- git config --global user.name "tripleabuilderbot"
- git tag $TAGGED_VERSION -a -m "$TAGGED_VERSION"
- git push -q https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/triplea-game/triplea --tags 2>&1 | sed 's|https://.*github|https://[secure]@github|'
deploy:
  provider: releases
  api_key:
    secure: nxaqYrkXLGL3W20/eCnf63DLjMrQAhEuW44jggh1/nI383goa+u6w0bBtWCxRdVzos7t4dpVfS6+kv6oIHacm9zVA+RYrqy5opzCJhq8lmXVVRijbALzUeiFif2HURMaKWj0ynRNVlAyBHzazPTLZVWywifpdSubSkuMWkl20cmuKu/Hg3c1EC9se3OYhhTHx3Hya7xSrctrDEYLsEBAUZzkKfscqRVqwwltS88CgIMtRISDpSBGrtH0t1uAH6NitTSguGgb+QEpqnELcRLymX2G1yzMA4Xr5c/L34MfbBKf8vIuG9t411xYuLoyKoUbroTWxSnPwlSy6PHz+QJ7UCXbDkATOGO3chxlKxglppvI/G3n2YP5Zf2dAaDlHblpvarh55i/4i4sKB2AbvvzkIHrQJwUgmLCbpN8/Vp9GWcGkd6i5U7F8tNInCs6ttX3oGvGOfYEXs02Ctyiea4LAqk4S7GZTuV2QXqxXglL4eRIwZ4UETiwgoAAtHma63Eq7+9t2ykMlk7zAK96FGwJrB97wa08aPuSxL94IYEBmn9Ht/vKXRiNQMvpnfp4rWQtL3cqbVyYAg5EjKb4PsBmnb91+RXtnWFOY1RpZGt8sPXYd+KZYzN1BXTFJEpaLLsIDN6r7nMcAvJDUmucaM+m7giPXz1ZBGAic3UBM1qMCgI=
  ## This is the list of files to be deployed to github releases
  file:
    - build/libs/triplea-${TAGGED_VERSION}-all.jar
    - build/releases/triplea_windows_${TAGGED_VERSION}.exe
    - build/releases/triplea_macos_${TAGGED_VERSION}.dmg
    - build/releases/triplea_unix_${TAGGED_VERSION}.sh
    - build/distributions/triplea-${TAGGED_VERSION}-all_platforms.zip
    - build/distributions/triplea-${TAGGED_VERSION}-bots.zip
    - build/distributions/triplea-${TAGGED_VERSION}-server.zip
  skip_cleanup: true
  prerelease: true
  on:
    repo: triplea-game/triplea
    tags: false
    branches:
      only:
        - master
