language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
      # python for map file splitter
      - python3
      - python3-yaml
install: true
services:
- postgresql
after_success: ./.travis/update_checkstyle_thresholds
before_deploy:
- ./.travis/install_install4j
- ENGINE_VERSION=$(grep "engine_version" game_engine.properties | sed 's/.*= *//g')
- TAGGED_VERSION="$ENGINE_VERSION.$TRAVIS_BUILD_NUMBER"
- ./.travis/build_installers $TAGGED_VERSION
- ./.travis/push_tag $TAGGED_VERSION
- ./.travis/push_maps
deploy:
  provider: releases
  api_key:
    secure: nxaqYrkXLGL3W20/eCnf63DLjMrQAhEuW44jggh1/nI383goa+u6w0bBtWCxRdVzos7t4dpVfS6+kv6oIHacm9zVA+RYrqy5opzCJhq8lmXVVRijbALzUeiFif2HURMaKWj0ynRNVlAyBHzazPTLZVWywifpdSubSkuMWkl20cmuKu/Hg3c1EC9se3OYhhTHx3Hya7xSrctrDEYLsEBAUZzkKfscqRVqwwltS88CgIMtRISDpSBGrtH0t1uAH6NitTSguGgb+QEpqnELcRLymX2G1yzMA4Xr5c/L34MfbBKf8vIuG9t411xYuLoyKoUbroTWxSnPwlSy6PHz+QJ7UCXbDkATOGO3chxlKxglppvI/G3n2YP5Zf2dAaDlHblpvarh55i/4i4sKB2AbvvzkIHrQJwUgmLCbpN8/Vp9GWcGkd6i5U7F8tNInCs6ttX3oGvGOfYEXs02Ctyiea4LAqk4S7GZTuV2QXqxXglL4eRIwZ4UETiwgoAAtHma63Eq7+9t2ykMlk7zAK96FGwJrB97wa08aPuSxL94IYEBmn9Ht/vKXRiNQMvpnfp4rWQtL3cqbVyYAg5EjKb4PsBmnb91+RXtnWFOY1RpZGt8sPXYd+KZYzN1BXTFJEpaLLsIDN6r7nMcAvJDUmucaM+m7giPXz1ZBGAic3UBM1qMCgI=
  ## This is the list of files to be deployed to github releases
  file:
    - build/libs/triplea-${TAGGED_VERSION}-all.jar
    - build/releases/TripleA_${TAGGED_VERSION}_windows-64bit.exe
    - build/releases/TripleA_${TAGGED_VERSION}_windows-32bit.exe
    - build/releases/TripleA_${TAGGED_VERSION}_macos.dmg
    - build/releases/TripleA_${TAGGED_VERSION}_unix.sh
    - build/distributions/triplea-${TAGGED_VERSION}-all_platforms.zip
    - build/distributions/triplea-${TAGGED_VERSION}-server.zip
  skip_cleanup: true
  prerelease: true
  on:
    tags: false
    repo: triplea-game/triplea
    branches:
      only:
        - master
