dist: trusty
sudo: false
language: java
matrix:
  include:
  - jdk: oraclejdk8
    env: TRIPLEA_RELEASE=true
  - jdk: oraclejdk9
    env: TRIPLEA_RELEASE=false
addons:
  postgresql: "9.5"
  apt:
    packages:
      # python for map file splitter
      - python3
      - python3-yaml
install:
## set up clean database, will be used later for integration test
 - echo "create database ta_users" | psql -h localhost -U postgres
## run database migration to create tables and test data inserts
 - ./gradlew flywayMigrate
before_script: ./.travis/setup_gpg
script:
## run all tests
- ./gradlew --parallel check jacocoTestReport
after_success:
## if checkstyle violation counts are lower, submit a automatic PR to update the current violation count.
- ./.travis/update_checkstyle_thresholds
## upload coverage report - https://github.com/codecov/example-gradle
- bash <(curl -s https://codecov.io/bash)
before_deploy:
## Update engine version property in-place, append build number.
## For example: "engine_version = 1.9.0.0" -> "engine_version = 1.9.0.0.1234"
- sed -i "s/^\(engine_version\s*=.*\)$/\1.${TRAVIS_BUILD_NUMBER}/" game-core/game_engine.properties
## Read the engine version number into a variable
- ENGINE_VERSION="$(grep engine_version game-core/game_engine.properties | sed 's/.*=\s*//g')"
## set lobby version variable to match engine version; the two for now are in sync.
- LOBBY_VERSION="$ENGINE_VERSION"
## install4j is a program to build executable installers
- ./.travis/install_install4j
## create OS specific installer application
- ./gradlew -PengineVersion="$ENGINE_VERSION" releaseInstallers
## create a universal java distributable that has assets and jar file packaged together
- ./gradlew -PengineVersion="$ENGINE_VERSION" releaseAllPlatformsJar
- ./.travis/generate_artifact_checksums
## tag push triggers deploy files to be uploaded to github releases.
- ./.travis/push_tag $ENGINE_VERSION
## read the maps in 'triplea_maps.yaml' and send info to json data dump that website
## reads. This will live update the maps page: http://triplea-game.org/maps-list/maps/
- ./.travis/push_maps
deploy:
  provider: releases
  api_key:
    secure: nxaqYrkXLGL3W20/eCnf63DLjMrQAhEuW44jggh1/nI383goa+u6w0bBtWCxRdVzos7t4dpVfS6+kv6oIHacm9zVA+RYrqy5opzCJhq8lmXVVRijbALzUeiFif2HURMaKWj0ynRNVlAyBHzazPTLZVWywifpdSubSkuMWkl20cmuKu/Hg3c1EC9se3OYhhTHx3Hya7xSrctrDEYLsEBAUZzkKfscqRVqwwltS88CgIMtRISDpSBGrtH0t1uAH6NitTSguGgb+QEpqnELcRLymX2G1yzMA4Xr5c/L34MfbBKf8vIuG9t411xYuLoyKoUbroTWxSnPwlSy6PHz+QJ7UCXbDkATOGO3chxlKxglppvI/G3n2YP5Zf2dAaDlHblpvarh55i/4i4sKB2AbvvzkIHrQJwUgmLCbpN8/Vp9GWcGkd6i5U7F8tNInCs6ttX3oGvGOfYEXs02Ctyiea4LAqk4S7GZTuV2QXqxXglL4eRIwZ4UETiwgoAAtHma63Eq7+9t2ykMlk7zAK96FGwJrB97wa08aPuSxL94IYEBmn9Ht/vKXRiNQMvpnfp4rWQtL3cqbVyYAg5EjKb4PsBmnb91+RXtnWFOY1RpZGt8sPXYd+KZYzN1BXTFJEpaLLsIDN6r7nMcAvJDUmucaM+m7giPXz1ZBGAic3UBM1qMCgI=
  file_glob: true
  file:
    - game-core/build/artifacts/*
    - lobby/build/distributions/lobby-$LOBBY_VERSION-server.zip
  ## This is set to true to not delete artifacts between the 'before-deploy' and 'deploy' steps
  skip_cleanup: true
  prerelease: true
  on:
    tags: false
    condition: "$TRIPLEA_RELEASE = true"
    repo: triplea-game/triplea
    branches:
      only:
        - master
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/1b12bfcd765b19e2d59d"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
