dist: xenial
sudo: false
language: java
if: tag is blank

# Note: Travis generally does not allocate more than 5 VMs at once.
# Avoid running more than 5 jobs in parallel. Try to keep the jobs
# balanced so that they each take about the same amount of time.

# Note: We download Java 11.0.5 for a few reasons:
# - jcenter no longer allows https TLS1.0 connection (this is seen as
#   a gradle failed to download plugin error)
# - Travis has Java 11.0.2 baked in to it, 11.0.2 does not have a
#   recent patch (2019-10) to allow Java 11 to use a compatible version
#   of TLS.
# To overcome this situation, we emulate the travis 'install-jdk' script
# and install a latest Java 11. For reference:
#   https://sormuras.github.io/blog/2017-12-08-install-jdk-on-travis.html
# Java12 does not have this issue, we do not download the Java11 script
# for that JVM or else we would be overriding Java12 with Java11.  
#
# Additional note: The export commands seem to not apply when extracted
# to a script and seemingly only work when located in the main travis config
# here.
#

jobs:
  include:
    - stage: verify
      env: DESCRIPTION="static verification"
      jdk: openjdk11
      before_install:
        - ./.travis/install_java_11.0.5
        - export JAVA_HOME=~/jdk-11.0.5+10
        - export PATH=${JAVA_HOME}/bin:$PATH
        - java --version
      install: skip
      script:
        ## shellcheck all shell scripts
        - find .travis/ -type f | xargs grep -lE "^#\!/bin/bash$" | xargs shellcheck
        - .travis/check-links || travis_terminate 1;
        - ./gradlew --no-daemon --parallel validateYamls spotlessCheck checkstyleMain checkstyleTest pmdMain
    - stage: verify
      env: DESCRIPTION="JDK11 integTest"
      jdk: openjdk11
      addons: {postgresql: "10"}
      before_install:
        - ./.travis/install_java_11.0.5
        - export JAVA_HOME=~/jdk-11.0.5+10
        - export PATH=${JAVA_HOME}/bin:$PATH
        - java --version
      install: skip
      script:
        - ./.travis/setup_database &
        - ./gradlew --no-daemon --parallel integTest
    - stage: verify
      env: DESCRIPTION="JDK12 unitTests"
      jdk: openjdk12
      install: skip
      script:
        - ./gradlew --no-daemon --parallel test
    - stage: verify
      jdk: openjdk11
      env: DESCRIPTION="JDK11 unitTests and Test Coverage"
      before_install:
        - ./.travis/install_java_11.0.5
        - export JAVA_HOME=~/jdk-11.0.5+10
        - export PATH=${JAVA_HOME}/bin:$PATH
        - java --version
      install: skip
      script:
        - ./gradlew --no-daemon --parallel test jacocoTestReport
        - bash <(curl -s https://codecov.io/bash)  # upload coverage report - https://github.com/codecov/example-gradle
    - stage: verify
      jdk: openjdk11
      env: DESCRIPTION="Smoke Test"
      addons: {postgresql: "10"}
      before_install:
        - ./.travis/install_java_11.0.5
        - export JAVA_HOME=~/jdk-11.0.5+10
        - export PATH=${JAVA_HOME}/bin:$PATH
        - java --version
      install: skip
      script:
        - ./.travis/setup_database
        - ./.travis/run_smoke_tests
    - stage: deploy
      if: (branch = master) and (repo = 'triplea-game/triplea') and (type != 'pull_request')
      install: skip
      before_install:
        - ./.travis/install_java_11.0.5
        - export JAVA_HOME=~/jdk-11.0.5+10
        - export PATH=${JAVA_HOME}/bin:$PATH
        - java --version
      script:
        - ./.travis/setup_gpg
        ## Update product version to include build number.
        ## EG: replace "2.0.0" to be "2.0.15555";
        - sed -i "s/.0$/.$TRAVIS_BUILD_NUMBER/" game-core/src/main/resources/META-INF/triplea/product.properties
        - ./.travis/do_release
      deploy:
        jdk: openjdk11
        provider: releases
        addons:
          apt:
            packages:
              # python for map file splitter
              - python3
              - python3-yaml
        api_key:
          secure: nxaqYrkXLGL3W20/eCnf63DLjMrQAhEuW44jggh1/nI383goa+u6w0bBtWCxRdVzos7t4dpVfS6+kv6oIHacm9zVA+RYrqy5opzCJhq8lmXVVRijbALzUeiFif2HURMaKWj0ynRNVlAyBHzazPTLZVWywifpdSubSkuMWkl20cmuKu/Hg3c1EC9se3OYhhTHx3Hya7xSrctrDEYLsEBAUZzkKfscqRVqwwltS88CgIMtRISDpSBGrtH0t1uAH6NitTSguGgb+QEpqnELcRLymX2G1yzMA4Xr5c/L34MfbBKf8vIuG9t411xYuLoyKoUbroTWxSnPwlSy6PHz+QJ7UCXbDkATOGO3chxlKxglppvI/G3n2YP5Zf2dAaDlHblpvarh55i/4i4sKB2AbvvzkIHrQJwUgmLCbpN8/Vp9GWcGkd6i5U7F8tNInCs6ttX3oGvGOfYEXs02Ctyiea4LAqk4S7GZTuV2QXqxXglL4eRIwZ4UETiwgoAAtHma63Eq7+9t2ykMlk7zAK96FGwJrB97wa08aPuSxL94IYEBmn9Ht/vKXRiNQMvpnfp4rWQtL3cqbVyYAg5EjKb4PsBmnb91+RXtnWFOY1RpZGt8sPXYd+KZYzN1BXTFJEpaLLsIDN6r7nMcAvJDUmucaM+m7giPXz1ZBGAic3UBM1qMCgI=
        file_glob: true
        file: build/artifacts/*
        skip_cleanup: true        
        prerelease: true
        on:
          tags: false
          repo: triplea-game/triplea
          branch: master
after_failure:
  - echo "================ Build step 'after_failure' =================" > /dev/null
  -  test "$TRAVIS_EVENT_TYPE" != "pull_request" && test "$TRAVIS_BRANCH" = master && ./.travis/report_build_status FAILURE
