#!/bin/bash

# Starts all local docker databases

set -eu

echo "Starting all databases.."
"$(dirname "$0")/lobby-db/start_docker_db"
"$(dirname "$0")/maps-db/start_docker_db"

bold="\e[1m"
bold_green="${bold}\e[32m"
normal="\e[0m"

echo ""
echo -e "[${bold_green}DONE${normal}] ${bold}All databases started!${normal}"
