#!/bin/bash

boldGreen="\e[1m\e[92m"
normal="\e[0m"

./gradlew --parallel spotlessApply check \
&& .travis/find-unmatched-test-packages \
&& .travis/find-orphaned-tests \
&& .travis/find-unused-dbunit-datasets \
&& .travis/check-custom-style \
&& echo -e "${boldGreen}SUCCESS${normal}"

