#!/bin/bash

boldGreen="\e[1m\e[92m"
normal="\e[0m"

spitfire-server/database/start_docker_db

./gradlew --parallel spotlessApply check \
&& .build/code-convention-checks/run \
&& .build/find-unused-or-unmatched-tests/run \
&& echo -e "${boldGreen}SUCCESS${normal}"
