http_server_user: http_server

http_server_folder: "/home/{{ http_server_user }}"

http_server_jar: "triplea-http-server-{{ lookup('env', 'VERSION') }}.jar"

http_server_port: "8080"

http_server_postgres_password: "{{ lobby_db_password }}"

http_server_postgres_host: "127.0.0.1"

http_server_postgres_port: "5432"

http_server_error_report_github_org: "triplea-game"

http_server_error_report_github_repo: "test"

http_server_error_report_github_token: "test"

http_server_config_file: configuration-prerelease.yml

http_server_db_user: "{{ lobby_db_user}}"

http_server_db_password: "{{ lobby_db_password }}"