http_server_user: http_server
http_server_port: "8080"
http_server_home_folder: "/home/{{ http_server_user }}"
http_server_run_file: "{{ http_server_home_folder }}/run_server"

http_server_jar: "triplea-http-server-{{ version }}.jar"

http_server_error_report_github_org: "triplea-game"
http_server_error_report_github_repo: "test"
http_server_error_report_github_token: "test"

http_server_db_host: "127.0.0.1"
http_server_db_port: "5432"

http_server_db_name: "{{ lobby_db_name }}"
http_server_db_user: "{{ lobby_db_user }}"

create_issues_github_api_token: test

