#!/bin/bash

# Run this script to drop current database data and
# load sample data. Sample data is very useful in particular
# for testing moderator, it creates a user "test:test" that
# has admin.
#
# Warning: any local running instances of the lobby server
# should be shutdown, or restarted after running this script.
# The active database connections become invalid when we
# drop database.

./drop_db
./run_flyway
./load_sample_data
