#!/bin/bash

set -u

database_port=5433
database_name=maps_db
database_user=maps_user

# Check if we can connect to database
if ! echo 'select 1' \
       | psql -h localhost -p "$database_port" -U "$database_user" "$database_name" 2> /dev/null \
       | grep -q '1 row';
then
 echo "ERROR: docker not running, start the database first"
 exit 1
fi

PSQL="psql -h localhost -U $database_user -p $database_port -w -d postgres"

echo "Force killing open connections to database"
echo "select pg_terminate_backend(pid) from pg_stat_activity where datname='$database_name';" | $PSQL
echo "drop database $database_name" | $PSQL
echo "create database $database_name" | $PSQL

echo "Deploying schema"
"$(dirname "$0")/../gradlew" flywayMigrate

echo "Loading sample data"
psql -h localhost -U lobby_user lobby_db < cat "$(dirname "$0")/sample_data.sql" 

