#!/bin/bash

# Runs 'flyway' which will execute the SQL statements used to set up database and schema.
# Note, a flyway migration file can only be run once. If it is altered and run again
# by flyway, flyway will abort. There is a table set up by flyway to record migration files
# and a SHA is recorded. Either delete that SHA value or recreated the database with
# the 'drop_db' script if altering an existing migration file.

# If a migration file has been run on production, it SHOULD NOT be altered.

../gradlew flywayMigrate
