#!/bin/bash

set -u

database_name=lobby_db
database_user=lobby_user
database_port=5432
docker_container_name=lobby-db
bold="\e[1m"
bold_green="${bold}\e[32m"
normal="\e[0m"


function main() {
  echo -e "[${bold_green}STARTING${normal}] ${bold}$database_name on port $database_port${normal}"

  docker run --rm -d --name="$docker_container_name" -p "$database_port:5432" "triplea/$docker_container_name"
  waitForDatabaseToStart

  PSQL="psql -h localhost -U $database_user -p $database_port -w -d postgres"
  echo "create database $database_name" | $PSQL

  echo "Deploying schema to $database_name"
  pwd
  "$(dirname "$0")/../gradlew" flywayMigrate

  echo "Loading sample data"
  psql -h localhost -U lobby_user lobby_db < "$(dirname "$0")/sample_data.sql"
  echo -e "[${bold_green}DONE${normal}] ${bold}$database_name${normal}"
}

function waitForDatabaseToStart() {
  echo -n "Waiting for Database $database_name start.."
  tryAttempt=0
  while ! (
    echo 'select 1' \
       | psql -h localhost -p "$database_port" -U "$database_user" "$database_name" 2> /dev/null \
       | grep -q '1 row'); do

    sleep 0.2
    echo -n .

    tryAttempt=$((tryAttempt+1))
    # timeout after 10s
    if [ "$tryAttempt" -gt 50 ]; then
      echo "Aborting DB startup (timed out)"
      exit 1
    fi
  done
  echo ""
}

main
