#!/bin/bash

set -eu

PSQL="psql -h localhost -U postgres"

export PGPASSWORD=postgres

# Check if we can connect to database
if ! echo 'select 1' \
       | $PSQL 2> /dev/null \
       | grep -q '1 row';
then
 echo "ERROR: docker not running, start the database first"
 exit 1
fi

echo "Force killing open connections to database"
echo "select pg_terminate_backend(pid) from pg_stat_activity where datname='lobby_db';" | $PSQL
echo "select pg_terminate_backend(pid) from pg_stat_activity where datname='maps_db';" | $PSQL
echo "drop database lobby_db" | $PSQL
echo "drop database maps_db" | $PSQL

scriptDir="$(dirname "$0")"
$PSQL <  "$scriptDir/sql/init/02-create-databases.sql"

echo "Deploying schema"
"$scriptDir/../gradlew" flywayMigrateAll

"$scriptDir/load_sample_data"
