#!/bin/bash

set -eu

./gradlew :lobby-server:shadowJar

# Lobby-server is normally launched (if needed) by integration tests.
# On Travis, the lobby-server output from this launch process is not printed.
# To fix this, we launch an lobby-server explicitly and output is then 
# successfully printed.  This is important so we can see error output 
# if we have cases where tests somehow only fail on Travis (EG: http-500)
readonly LOBBY_SERVER_JAR_PATH=$(find lobby-server/build/libs/ -type f -name "*.jar")
java -jar "$LOBBY_SERVER_JAR_PATH" server ./lobby-server/configuration.yml &

