#!/bin/bash

set -eEux

.travis/shared/setup-database
mv maps-server/src/test/resources/dbunit-travis.yml maps-server/src/test/resources/dbunit.yml
export MAPS_SERVER_DB_PORT="5432"
./gradlew integTest -x :smoke-testing:integTest
