#!/bin/bash

set -eu

bold="\e[1m"
bold_green="${bold}\e[32m"
normal="\e[0m"

function main() {
  echo -e "[${bold_green}STARTING DATABASE${normal}]"

  runDocker
  waitForDatabaseToStart
  echo -e "[${bold_green}DONE${normal}]"
}

function runDocker() {
  echo "Stopping database.."
  docker stop database || echo "[OK] Database not running.."
  docker run \
    --rm -d \
    --name="database" \
    -e "POSTGRES_PASSWORD=postgres" \
    -p "5432:5432" \
    -v "$(pwd)/$(dirname "$0")/sql/init/:/docker-entrypoint-initdb.d/" \
    "postgres:10"
}

function waitForDatabaseToStart() {
  echo -n "Waiting for Database start.."
  tryAttempt=0
  export PGPASSWORD=postgres
  while ! (
    echo 'select 1' \
       | psql -h localhost -U postgres 2> /dev/null \
       | grep -q '1 row'); do

    sleep 0.2
    echo -n .

    tryAttempt=$((tryAttempt+1))
    # timeout after 10s
    if [ "$tryAttempt" -gt 50 ]; then
      echo "Aborting DB startup (timed out)"
      exit 1
    fi
  done
  echo ""
}

main
