#!/bin/bash

set -eu

URI_FILE=$(find . -type f -path "*/src/main/java/*" -name "UrlConstants.java")
green="\e[32m"
end="\e[0m"
FAILURE_PREFIX="Failed with Code: "

if [ -z "$URI_FILE" ]; then
  echo "Error could not find file 'UrlConstants.java'"
  exit 1
fi



function checkUri() {
  local -r uri="$1"
  local output
  if ! output="$FAILURE_PREFIX$(curl -Lsf -o /dev/null -w "%{http_code}" "$uri")"; then
    reportBrokenUri "$uri" "$output"
  fi
}

function reportBrokenUri() {
  FAILURE=1 
  local -r red="\e[38;5;196m"
  local -r blue="\e[38;5;75m"
  local -r error_reason=${2//${FAILURE_PREFIX}000/Connection Failure!}
  echo -e "Error: ${red}${1}${end} ${error_reason}${blue}${end}"
}

FAILURE=0

while read -r uri; do
  checkUri "$uri";
done < <(sed 's/^.*"\(.*\)".*$/\1/' "$URI_FILE" | grep "http")

if [ "$FAILURE" == 0 ]; then
  echo -e "${green}Links are valid${end}"
fi
exit "$FAILURE"

