#!/bin/bash

set -eux


function createDatabase() {
  local dbName="$1"
  local dbUser="$2"
  
  echo "create database ${dbName}" | psql -h localhost -U postgres -d postgres
  echo "create user ${dbUser} with password 'postgres'" | psql -h localhost -U postgres -d postgres
  echo "alter database ${dbName} owner to ${dbUser}" | psql -h localhost -U postgres -d postgres
}


createDatabase "lobby_db" "lobby_user"
createDatabase "maps_db" "maps_user"

./gradlew flywayMigrate -Pmaps_db_port=5432

