package org.triplea.http.client.web.socket.messages;

import com.google.gson.Gson;
import javax.annotation.Nonnull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import org.triplea.domain.data.ApiKey;

/**
 * A message that is generated by client and sent to the server. This object is intended to be
 * convertted to a JSON string and then sent.
 */
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class ClientMessageEnvelope {
  private static final Gson gson = new Gson();

  /** API key is used to identify the sender and must be valid on the server. */
  @Nonnull private final String apiKey;

  @Getter @Nonnull private final String messageType;
  @Getter @Nonnull private final String payload;

  public static ClientMessageEnvelope fromJson(final String jsonString) {
    return gson.fromJson(jsonString, ClientMessageEnvelope.class);
  }

  public ApiKey getApiKey() {
    return ApiKey.of(apiKey);
  }
}
