#!/bin/bash

set -u

function main() {
   set -x
  .build/setup-database
  ./gradlew --quiet test jacocoTestReport --exclude-task :smoke-testing:test
  result="$?"
  set +x
  # Run coverage reports only if tests passed

  if [ "$result" = 0 ]; then
    echo "Uploading test coverage reports"
    # upload coverage report to codecov - https://github.com/codecov/example-gradle
    bash <(curl -s https://codecov.io/bash)
  fi

  return $result
}


main

