#!/bin/bash

set -u

function main() {
  .build/setup-database
  ./gradlew test jacocoTestReport \
     --exclude-task :spitfire-server:lobby-module:test \
     --exclude-task :spitfire-server:maps-module:test \
     --exclude-task :spitfire-server:dropwizard-server:test
  result="$?"

  if [ "$result" = 0 ]; then
  ./gradlew \
     :spitfire-server:lobby-module:test \
     :spitfire-server:maps-module:test \
     :spitfire-server:dropwizard-server:test

     result="$?"
  fi

  # Run coverage reports only if tests passed
  if [ "$result" = 0 ]; then
    echo "Uploading test coverage reports"
    # upload coverage report to codecov - https://github.com/codecov/example-gradle
    bash <(curl -s https://codecov.io/bash)
  fi

  return $result
}


main

