- name: Ensure latest bash and ssl
  become: true
  apt:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - bash
      - openssl
      - libssl-dev
      - libssl-doc

- name: Install PostgreSQL
  become: true
  apt:
    state: present
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Set postgres user password
  become: true
  become_user: postgres
  postgresql_user:
    name: postgres
    login_password: "{{ postgres_user_db_password }}"
    password: "{{ postgres_user_db_password }}"
    encrypted: yes

