#
# This is the main ansible playbook to deploy TripleA server software.
# See the README.md files for details on running and testing.
#

- hosts:
    - postgresHosts
    - dropwizardHosts
    - botHosts
  gather_facts: no
  serial: 100%
  strategy: free
  roles:
    - apt_update
    - admin_user
    - firewall
    - security

- hosts: postgresHosts
  gather_facts: no
  serial: 100%
  strategy: free
  tags: lobbyDb
  roles:
    - postgres
    - flyway

- hosts: dropwizardHosts
  gather_facts: no
  serial: 100%
  strategy: free
  roles:
    - java
    - nginx
    - dropwizard

- hosts: botHosts
  gather_facts: no
  serial: 100%
  roles:
    - java
    - bot
