- hosts: all
  roles:
    - system/apt_common_tools
    - system/hostname
    - system/firewall
    - system/journald
    - system/admin_user

- hosts: forums
  tags: forums
  roles:
    - nginx_forums_conf

- hosts: lobbyServer
  tags: [lobby, lobby_server]
  roles:
    - java
    - {name: database/postgres, tags: database}
    - {name: database/flyway, tags: flyway}
    - {name: nginx, tags: nginx}
    - postfix
    - lobby_server

- hosts: letsEncrypt
  tags: lobby
  roles:
    - certbot

- hosts: botHosts
  tags: [bot, bots]
  roles:
    - java
    - bot

