#
# This is the main ansible playbook to deploy TripleA server software.
# See the README.md files for details on running and testing.
#

- hosts:
    - ansibleMasterHost
    - httpServerHosts
    - lobbyHosts
    - botHosts
  gather_facts: no
  serial: 100%
  strategy: free
  roles:
    - apt_update
    - admin_user
    - firewall
    - security

- hosts: httpServerHosts
  gather_facts: no
  serial: 100%
  strategy: free
  roles:
    - java
    - nginx
    - http_server

- hosts: lobbyHosts
  gather_facts: no
  serial: 100%
  strategy: free
  roles:
    - java
    - lobby

- hosts: botHosts
  gather_facts: no
  serial: 100%
  roles:
    - java
    - bot
