- hosts: all
  tags: system
  roles:
    - system/hostname
    - system/apt_update
    - system/firewall
    - system/security
    - system/journald

- hosts: support
  tags: support
  roles:
    - system/admin_user
    - system/apt_common_tools
    - support/log_aggregation_server

- hosts: forums
  tags: forums
  roles:
    - system/admin_user
    - system/apt_common_tools
    - nginx_forums_conf

- hosts: lobbyServer
  tags: [lobby, lobby_server]
  roles:
    - system/admin_user
    - system/apt_common_tools
    - java
    - database/postgres
    - {name: database/flyway, tags: flyway}
    - lobby_server
    - nginx
    - postfix
    - support/log_aggregation_sender


- hosts: mapsServer
  tags: [maps_server]
  roles:
    - system/admin_user
    - system/apt_common_tools
    - java
    - database/postgres
    - {name: database/flyway, tags: flyway}
    - maps_server
    - nginx
    - support/log_aggregation_sender

- hosts: letsEncrypt
  tags: lobby
  roles:
    - certbot
    # Re-run nginx role to fix configuration and do final restart.
    # Modifications to /etc/nginx/sites-enabled/default triggers a NGINX restart.
    # Certbot role adds a new line to /etc/nginx/sites-enabled/default
    # every time it runs and makes changes.
    - nginx

- hosts: botHosts
  tags: [bot, bots]
  roles:
    - system/apt_common_tools
    - java
    - bot
    - support/log_aggregation_sender

