- name: allow ports
  ufw:
    rule: allow
    port: "40{{ item }}"
    proto: tcp
  with_items: "{{ bot_numbers }}"

- name: create service user to run the app
  user:
    name: "{{ bot_user }}"
    create_home: yes
    system: yes

- name: deploy scripts to admin home
  template:
    src: "{{ item }}.j2"
    dest: "{{ admin_home }}/{{ item }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0755"
  with_items:
    - start-all
    - stop-all
    - download-all-maps

- name: create maps folder
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"
  with_items:
    - "{{ bot_install_home }}"
    - "{{ bot_maps_folder }}"

- name: deploy game-headless-zip file
  copy:
    src: "triplea-game-headless.zip"
    dest: "{{ bot_install_home }}/triplea-game-headless.zip"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: extract zip file
  unarchive:
    remote_src: yes
    src: "{{ bot_install_home }}/triplea-game-headless.zip"
    dest: "{{ bot_install_home }}/"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: create triplea-root touch file
  file:
    state: touch
    path: "{{ bot_install_home }}/.triplea-root"
    mode: "0644"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: deploy run_server script
  template:
    src: run_server.j2
    dest: "{{ bot_install_home }}/run_server"
    mode: "755"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: install systemd service script
  template:
    src: bot.service.j2
    dest: /lib/systemd/system/bot@.service
    mode: "644"

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enable and ensure bots are started
  service:
    name: "bot@{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ bot_numbers }}"
