- name: allow ports
  become: true
  ufw:
    rule: allow
    port: "40{{ item }}"
    proto: tcp
  with_items: "{{ bot_numbers }}"

- name: apt install unzip
  become: true
  apt:
    name: unzip
    state: present

- name: create service user to run the app
  become: true
  user:
    name: "{{ bot_user }}"
    create_home: yes
    system: yes

- name: deploy scripts to admin home
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "{{ admin_home }}/{{ item }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0755"
  with_items:
    - start-all
    - stop-all
    - download-all-maps

- name: create maps folder
  become: true
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"
  with_items:
    - "{{ bot_install_home }}"
    - "{{ bot_maps_folder }}"

- name: deploy jar file if using latest
  when: using_latest
  become: true
  copy:
    src: "triplea-game-headless-{{ version }}-all.jar"
    dest: "{{ bot_jar }}"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: create triplea-root touch file
  become: true
  file:
    state: touch
    path: "{{ bot_install_home }}/.triplea-root"
    mode: "0644"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: download zip file if not using latest
  when: not using_latest
  become: true
  get_url:
    url: "{{ zip_download }}"
    dest: "{{ bot_install_home }}/triplea-game-headless-{{ version }}.zip"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: extract zip file if not using latest
  when: not using_latest
  become: true
  unarchive:
    remote_src: yes
    src: "{{ bot_install_home }}/triplea-game-headless-{{ version }}.zip"
    dest: "{{ bot_install_home }}/"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: move jar file to expected location if not using latest
  when: not using_latest
  become: true
  copy:
    remote_src: true
    src: "{{ bot_install_home }}/bin/triplea-game-headless-{{ version }}-all.jar"
    dest: "{{ bot_jar }}"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: deploy run_server script
  become: true
  template:
    src: run_server.j2
    dest: "{{ bot_folder }}/run_server"
    mode: "755"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: install systemd service script
  become: true
  template:
    src: bot.service.j2
    dest: /lib/systemd/system/bot@.service
    mode: "644"

- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: restart bots if deploying latest
  when: using_latest
  become: true
  service:
    name: "bot@{{ item }}"
    state: restarted
    enabled: yes
  with_items: "{{ bot_numbers }}"

- name: enable and ensure bots are started
  when: not using_latest
  become: true
  service:
    name: "bot@{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ bot_numbers }}"
