#!/bin/bash

# This script builds deployment artifacts from source and moves
# those artifacts to ansible 'file' locations where they are then
# available to ansible.

scriptDir="$(dirname "$0")"
rootDir="$scriptDir/../.."

BUILD_VERSION=$("$rootDir/.build/get-build-version")
MIGRATIONS_ZIP="$rootDir/spitfire-server/database/build/artifacts/migrations.zip"
LOBBY_SERVER_ZIP="$rootDir/spitfire-server/dropwizard-server/build/artifacts/triplea-dropwizard-server-$BUILD_VERSION.zip"
BOT_ZIP="$rootDir/game-app/game-headless/build/artifacts/triplea-game-headless-$BUILD_VERSION.zip"


function main() {
  buildArtifacts
  copyBuildArtifacts
}

function buildArtifacts() {
  (
    cd "$rootDir" || exit 1

    # Run a clean if artifacts do not exist. We may have already built the artifact
    # but with a different  SHA, in which case gradle will not generate them.
    if [ ! -f "$MIGRATIONS_ZIP" ]; then
      ./gradlew :spitfire-server:database:clean
    fi
    if [ ! -f "$LOBBY_SERVER_ZIP" ]; then
      ./gradlew :spitfire-server:dropwizard-server:clean
    fi
    if [ ! -f "$BOT_ZIP" ]; then
      ./gradlew :game-app:game-headless:clean
    fi

    ./gradlew \
        :spitfire-server:dropwizard-server:release \
        :game-app:game-headless:release \
        :spitfire-server:database:release
        set +x
  )
}

function copyBuildArtifacts() {
  BUILD_VERSION=$("$rootDir/.build/get-build-version")
  copyBuildArtifact "$MIGRATIONS_ZIP" "$scriptDir/../ansible/roles/lobby_server/files/"
  copyBuildArtifact "$LOBBY_SERVER_ZIP" "$scriptDir/../ansible/roles/lobby_server/files/"
  copyBuildArtifact "$BOT_ZIP" "$scriptDir/../ansible/roles/bot/files/"
}

function copyBuildArtifact() {
  local -r artifactSource="$1"
  local -r artifactDestinationPath="$2"

  if [ ! -f "$artifactSource" ]; then
    echo "Error: File does not exist: $artifactSource"
    exit 1
  fi

  mkdir -p "$artifactDestinationPath"
  cp -v "$artifactSource" "$artifactDestinationPath"
}

main

