#!/bin/bash

# This script builds deployment artifacts from source and moves
# those artifacts to ansible 'file' locations where they are then
# available to ansible.

VERSION="${1-}"

if [ -z "$VERSION" ]; then
  echo "Error, missing 'version' argument"
  echo "Usage: $0 [version]"
  exit 1
fi

function main() {
  buildArtifacts
}

function buildArtifacts() {
  (
    cd ..
    ./gradlew \
        :servers:lobby-server:release \
        :servers:maps-server:release \
        :game-headless:release \
        :servers:database:release
  )
  copyBuildArtifact "../servers/database/build/artifacts/migrations.zip" "ansible/roles/database/flyway/files/"
  copyBuildArtifact "../servers/lobby-server/build/artifacts/triplea-lobby-server-$VERSION.zip" "ansible/roles/lobby_server/files/"
  copyBuildArtifact "../servers/maps-server/build/artifacts/triplea-maps-server-$VERSION.zip" "ansible/roles/maps_server/files/"
  copyBuildArtifact "../game-headless/build/artifacts/triplea-game-headless-$VERSION.zip" "ansible/roles/bot/files/"
}

function copyBuildArtifact() {
  local -r artifactSource="$1"
  local -r artifactDestinationPath="$2"

  if [ ! -f "$artifactSource" ]; then
    echo "Error: File does not exist: $artifactSource"
    exit 1
  fi

  mkdir -p "$artifactDestinationPath"
  cp -v "$artifactSource" "$artifactDestinationPath"
}

main

