bot_user: "bot"

bot_folder: "/home/{{ bot_user }}"

bot_jar: "triplea-game-headless-{{ lookup('env', 'VERSION') }}.jar"

bot_maps_folder: "{{ bot_folder }}/maps"

bot_lobby_host: "{{ bot_lobby_address }}"

bot_max_memory: "168m"

bot_name: "BotServer"

bot_lobby_address: "{{ lobby_address }}"

