bot_user: "bot"

bot_folder: "/home/{{ bot_user }}"

bot_jar: "triplea-game-headless-{{ version }}.jar"

bot_maps_folder: "{{ bot_folder }}/maps"

bot_lobby_uri: "{{ lobby_uri }}"

bot_max_memory: "168m"

bot_name: "BotServer"

bot_ports:
  - 4001
  - 4002
  - 4003
  - 4004
