- name: install software properties common
  become: true
  apt:
    state: present
    name: software-properties-common
  
- name: install certbot apt-repositories
  become: true
  apt_repository:
    state: present
    repo: "{{ item }}"
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"
    - "ppa:certbot/certbot"

- name: install certbot and python for certbot on nginx
  become: true
  apt:
    update_cache: yes
    name:
      - certbot
      - python-certbot-nginx

- name: look for certbot generated key file
  become: true
  stat:
    path: /etc/letsencrypt/live/{{ inventory_hostname }}/cert.pem
  register: has_certbot_pem

- name: run certbot
  become: true
  command: "certbot --nginx -n -m tripleabuilderbot@gmail.com --agree-tos -d {{ inventory_hostname }}"
  when: has_certbot_pem.stat.exists == false

- name: Add letsencrypt cronjob for cert renewal
  become: true
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: certbot renew

