Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
  end

  config.vm.define "vagrantHost" do |vagrantHost|
    vagrantHost.vm.network "forwarded_port", guest: 22, host: 2010, host_ip: "127.0.0.1", id: "ssh"
    vagrantHost.vm.network "forwarded_port", guest: 4001, host: 4100, host_ip: "127.0.0.1"
    vagrantHost.vm.network "forwarded_port", guest: 443, host: 8000, host_ip: "127.0.0.1"
    vagrantHost.vm.network "forwarded_port", guest: 8080, host: 8008, host_ip: "127.0.0.1"
  end
end

