#!/bin/bash

## Builds TripleA game-installers and build artifacts suitable
## for distribution.  Build artifacts will be created for each
## sub-project and copied into: './build/artifacts'

## install install4j
set -x

function main() {
  install_install4j
  build_installers
  collect_artifacts
}

# Installs install4j, the license key is injected into install4j during this step.
function install_install4j() {
  INSTALL4J_HOME=/tmp/install4j
  mkdir $INSTALL4J_HOME

  echo "Downloading and installing install4j to '$INSTALL4J_HOME'"
  wget --no-verbose -O install4j_unix.sh \
  https://raw.githubusercontent.com/triplea-game/assets/master/install4j/install4j_unix_8_0_7.sh
  chmod +x install4j_unix.sh
  ./install4j_unix.sh -q -dir "$INSTALL4J_HOME"
  "$INSTALL4J_HOME/bin/install4jc" -L "$INSTALL4J_LICENSE"
}


## Runs gradle command that creates the installer executables, uses intall4j
function build_installers() {
  JAVA_OPTS=-Xmx4G ./gradlew \
      --no-daemon \
      --parallel \
      -Pinstall4jHomeDir="$INSTALL4J_HOME" \
      release
}

## Gathers built artifacts from all sub-projects to a single top-level to
## include with the release
function collect_artifacts() {
  readonly ARTIFACTS_DIR=./build/artifacts
  mkdir -p $ARTIFACTS_DIR
  cp ./*/build/artifacts/* ${ARTIFACTS_DIR}
  find $ARTIFACTS_DIR
}

main

