#!/bin/bash

# Overwrites the game-headed 'product.properties' file to have an updated build version

scriptDir=$(dirname "$0")
rootDir="$scriptDir/.."
buildVersion=$($scriptDir/get-build-version)

set -x

echo "version = $buildVersion" > \
  "$rootDir/game-app/game-core/src/main/resources/META-INF/triplea/product.properties"
