#!/bin/bash

# Updates version file to have an updated build number.
# Params:
#  runNumber: [required] run number, or build number
#  githubSha: [optional] used as a an additional version number, only
#     the first 10 characters are used

set -x
runNumber="$1"
githubSha="$2"

PROP_FILE="game-core/src/main/resources/META-INF/triplea/product.properties"


versionSuffix="$runNumber"
if [ ! -z "$githubSha" ]; then
  # if githubSha is specified, append the version value with the first 10
  # characters of the SHA
  versionSuffix="$versionSuffix.$(echo "$githubSha" | cut -c 1-10)"
fi

## Update property file, set build number
## Expect contents like: "version = 2.0.0"
## Overwrite to contain something like: "version = 2.0.1234"

sed -i "s/\(version *=.*\)$/\1.$versionSuffix/" $PROP_FILE

## Read the new version number and print it.
## EG: "version = 2.0.1234", print "2.0.1234"
## Do this by:
## 1. remove all spaces, EG: "version=2.0.1234"
## 2. remove everything up to and including the equals sign, eg: "2.0.1234"

sed 's/.*= *//' $PROP_FILE

