#!/bin/bash

# Updates version file to have an updated build number.
# Params:
#  runNumber: [required] run number, or build number
#

set -x
runNumber="$1"

PROP_FILE="game-app/game-core/src/main/resources/META-INF/triplea/product.properties"

## Update property file, set build number
## Expect contents like: "version = 2.0.0"
## Overwrite to contain something like: "version = 2.0.1234"

sed -i "s/\(version *=.*\)$/\1.$runNumber/" $PROP_FILE

## Read the new version number and print it.
## EG: "version = 2.0.1234", print "2.0.1234"
## Do this by:
## 1. remove all spaces, EG: "version=2.0.1234"
## 2. remove everything up to and including the equals sign, eg: "2.0.1234"

sed 's/.*= *//' $PROP_FILE

