#!/bin/bash

set -eux

function main() {
  export PGPASSWORD=postgres
  createDatabase "lobby_db" "lobby_user" "lobby"
  createDatabase "error_report" "error_report_user" "error_report"
  ./gradlew flywayMigrateLobbyDb flywayMigrateErrorReportDb
}

function createDatabase() {
  local dbName="$1"
  local dbUser="$2"
  local password="$3"
  
  echo "create user ${dbUser} with password '${password}'" | psql -h localhost -U postgres -d postgres
  echo "create database ${dbName} owner ${dbUser}" | psql -h localhost -U postgres -d postgres
}

main
