#!/bin/bash

set -eux


function createDatabase() {
  local dbName="$1"
  local dbUser="$2"
  
  echo "create user ${dbUser} with password 'postgres'" | psql -h localhost -U postgres -d postgres
  echo "create database ${dbName} owner ${dbUser}" | psql -h localhost -U postgres -d postgres
}

export PGPASSWORD=postgres
createDatabase "lobby_db" "lobby_user"
createDatabase "maps_db" "maps_user"

./gradlew flywayMigrateAll

