#!/bin/bash

set -eEux

version=$(.travis/shared/set-version-number)

eval "$(ssh-agent -s)"

echo "$ANSIBLE_VAULT_PASSWORD" > vault_password
cd infrastructure
./run_ansible_prerelease "$version" -i ansible/inventory/prerelease
 
