#!/bin/bash

set -eEux

version=$(.travis/shared/set-version-number)

eval "$(ssh-agent -s)"

cd infrastructure
./build_deployment_artifacts
echo "$ANSIBLE_VAULT_PASSWORD" > vault_password
./run_deployment "$version" -i ansible/inventory/prerelease 

