- name: Ensure latest bash and ssl
  become: true
  apt:
    state: latest
    name:
      - bash
      - openssl
      - libssl-dev
      - libssl-doc

- name: Install PostgreSQL
  become: true
  apt:
    state: present
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Set postgres user password
  become: true
  become_user: postgres
  no_log: true
  postgresql_user:
    name: postgres
    login_password: "{{ postgres_user_db_password }}"
    password: "{{ postgres_user_db_password }}"
    encrypted: yes

- name: Create application database users
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    login_password: "{{ item.password }}"
    encrypted: yes
    state: "present"
  loop: "{{ databases }}"
  loop_control:
    label: "{{ item.user }}"

- name: Create application databases
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.user }}"
  loop: "{{ databases }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure user has access to the database
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ item.name }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    login_password: "{{ item.password }}"
    encrypted: yes
    priv: "ALL"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: "present"
  loop: "{{ databases }}"
  loop_control:
    label: "{{ item.name }} {{ item.user }}"

# This is a hack because the previous tasks were supposed to set
# the DB level password for our DB user, but it typically does not.
# To achieve this, we'll run the native SQL commands to set the
# user DB password.
- name: check if password is valid
  shell: >
      echo "select 1" |  psql -h localhost -U {{ lobby_db_user }} {{ lobby_db_name }}
      || echo "alter role {{ item.user }} with password '{{ item.password }}';"  | sudo -u postgres psql
  environment:
    PGPASSWORD: "{{ postgres_user_db_password }}"
  changed_when: false
  loop: "{{ databases }}"
  loop_control:
    label: "{{ item.user }}"

