#!/bin/bash

set -eEux

eval "$(ssh-agent -s)"
cd infrastructure || exit 1
VAULT_PASSWORD_FILE="vault_password"
echo "$ANSIBLE_VAULT_PASSWORD" > "$VAULT_PASSWORD_FILE"

ansible-vault view --vault-password-file="$VAULT_PASSWORD_FILE" ansible_ssh_key.ed25519 | ssh-add -

ansible-playbook \
  -i ansible/inventory/production \
  ansible/site.yml

