#!/bin/bash

# Prints the current build version, this is the product version plus current commit number
# Example output: 2026.06.15.23400

set -eu

scriptDir=$(dirname "$0")

cal_date=$(date -u +%Y.%m)
release_number=$(cat "$scriptDir/product-version.txt")
build_number=$(git rev-list --count HEAD)

echo "${cal_date}.${release_number}.${build_number}"
