#!/bin/bash

# Overwrites the game-headed 'product.properties' file to have an updated build version

set -e
scriptDir=$(dirname "$0")

(
  cd "$scriptDir" || exit 1
  rootDir=$(git rev-parse --show-toplevel)
  cd "$rootDir" || exit 1

  buildVersion=$(./gradlew -q printReleaseVersion)
  productPropertiesFile=$(find "$scriptDir/../../" -path "*src/main/resources/META-INF/*" -name "product.properties" -type f)
  echo "version = $buildVersion" | tee "$productPropertiesFile"
)
