#!/bin/bash -e
#
# This script sets up GnuPG (GPG) for use during a Travis build.
#

if [[ -z "$GPG_PRIVATE_KEY" ]]; then
  echo "GPG_PRIVATE_KEY not set; GPG operations will not be available in this build"
else
  gpg2 --batch --import <(echo "$GPG_PRIVATE_KEY")
fi
