# Shared variables, these variables are used across multiple roles.
# Other than these variables, roles should be fully self-contained.

java_open_jdk_version_major: "11"

lobby_db_name: lobby
lobby_db_user: triplea_lobby
lobby_db_password: "{{ lookup('ENV', 'POSTGRES_PASSWORD') }}"
lobby_port: 3304
bot_lobby_port: "{{ lobby_port }}"

http_server_port: "4567"
