# These variables are used across multiple roles.
# Other than these variables, roles should be fully self-contained.

ansible_connection: ssh
ansible_user: root

java_open_jdk_version_major: "11"
lobby_db_name: lobby_db
lobby_db_user: lobby_user
version: "{{ lookup('env', 'VERSION') }}"

