# Other than these variables, roles should be fully self-contained.
# Shared variables, these variables are used across multiple roles.

ansible_connection: ssh
ansible_user: root

java_open_jdk_version_major: "11"
lobby_db_name: lobby_db
# TODO: Project#12 encrypt this value
lobby_db_password: "vagrant-db-password"
lobby_db_user: lobby_user
version: "{{ lookup('env', 'VERSION') }}"

