#!/bin/bash

set -eEu

## shellcheck all shell scripts
find .travis/ -type f -print0 | xargs --null grep -lE "^#\!/bin/bash$" | xargs shellcheck

script_dir=$(dirname "$0")
"$script_dir/check-custom-style"

