#!/bin/bash
#
# Builds the installer files that would be deployed to github releases.
# .travis.yml names the files that will be deployed, those files are outputs from this task.
#
# To build the installers we use gradle for the heavy lifting. Gradle does the java compile
# and packaging and runs install4j to generate the final installer files.
#

export TAGGED_VERSION=$1

## update engine version number to have the build number
sed -i "s/engine_version.*/engine_version = $TAGGED_VERSION/" game_engine.properties

## java package and runs install4j
./gradlew release
