#!/bin/bash

set -u

green="\e[92m"
blue="\e[34m"
normal="\e[0m"
bold="\e[1m"

javaFiles=$(mktemp)
sqlFiles=$(mktemp)
trap 'rm $javaFiles $sqlFiles' EXIT

find . -type f -name "*.java" > "$javaFiles"
find lobby-db/src/main/resources -type f -name "*.sql" > "$sqlFiles"

status=0


function main() {
  favorJava9CollectionsApi
  referToCollectionsByInterfaceType
  legacyApi
  databaseNamesAreLowerSnakeCase
  databaseTablesAreSingular
}

function favorJava9CollectionsApi() {
  echo -e "${bold}${blue}Verifying preference to use List.of(), Map.of() and Set.of() compared to java.util.Collections.*${normal}"
  echo -e "${blue}Example: instead of 'Collections.singleton(value)', use 'Set.of(value)'${normal}"
  local found=0

  while read -r file; do
    grep --color=auto -H -f .travis/style.include/disallowed-collection-calls "$file" && status=1 && found=1
    grep --color=auto -H -f .travis/style.include/disallowed-collection-imports "$file" && status=1 && found=1
  done <<< "$(cat "$javaFiles")"

  if [ "$found" -eq 0 ]; then
    echo -e "${green}[OK]${normal}"
  fi
  echo ""
}

function referToCollectionsByInterfaceType() {
  echo -e "${bold}${blue}Assign to collection types using their interface${normal}"
  echo -e "${blue}Ex: instead of 'ArrayList<String> list =', use 'List<String> list = '${normal}"
  local found=0

  while read -r file; do
    grep --color=auto -E -H -f .travis/style.include/concrete-collection-types "$file" && status=1 && found=1
  done <<< "$(cat "$javaFiles")"

  if [ "$found" -eq 0 ]; then
    echo -e "${green}[OK]${normal}"
  fi
  echo ""
}

function legacyApi() {
  echo -e "${bold}${blue}Do not use legacy API tools like Vector${normal}"
  local found=0

  while read -r file; do
    grep --color=auto -H -f .travis/style.include/legacy-api "$file" && status=1 && found=1
  done <<< "$(cat "$javaFiles")"
  
  if [ "$found" -eq 0 ]; then
    echo -e "${green}[OK]${normal}"
  fi
  echo ""
}

function databaseNamesAreLowerSnakeCase() {
  echo -e "${bold}${blue}Database entities should not be camelCased, lower_snake_case instead.${normal}"
  echo -e "${blue}Ex: instead of 'tableName' use 'table_name'${normal}"
  local found=0
  
  while read -r file; do
    grep --color=auto -H -E "[a-z][A-Z]" "$file" && status=1 && found=1
  done <<< "$(cat "$sqlFiles")"

  if [ "$found" -eq 0 ]; then
    echo -e "${green}[OK]${normal}"
  fi
  echo ""
}
  

function databaseTablesAreSingular() {
  echo -e "${bold}${blue}Database tables should be singular${normal}"
  echo -e "${blue}Ex: instead of 'create table words' use 'create table word'${normal}"
  local found=0
  
  while read -r file; do
    grep --color=auto -H -E -i "create table.*s$" "$file" && status=1 && found=1
  done <<< "$(cat "$sqlFiles")"


  if [ "$found" -eq 0 ]; then
    echo -e "${green}[OK]${normal}"
  fi
  echo ""
}

main

exit "$status"

