#!/bin/bash -e
#
# This script collects artifacts from all subprojects to a single folder in
# preparation for release.
#

readonly ARTIFACTS_DIR=./build/artifacts

mkdir -p ${ARTIFACTS_DIR}

cp -v ./**/build/artifacts/* ${ARTIFACTS_DIR}
