#!/bin/bash

echo "create database lobby_db" | psql -h localhost -U postgres -d postgres
echo "create user lobby_user with password 'postgres'" | psql -h localhost -U postgres -d postgres
echo "alter database lobby_db owner to lobby_user" | psql -h localhost -U postgres -d postgres
sed -i "s/.0$/.$TRAVIS_BUILD_NUMBER/" game-core/src/main/resources/META-INF/triplea/product.properties
RELEASE_VERSION=$(sed 's/version\s*=\s*//' game-core/src/main/resources/META-INF/triplea/product.properties)
./gradlew flywayMigrate
./gradlew shadowJar
 # Http server needs to be launched to supprt integ testing. Launching it here allows output from the server to go to the travis log.
java -jar http-server/build/libs/triplea-http-server-${RELEASE_VERSION}.jar server ./http-server/configuration-prerelease.yml &


