#!/bin/bash

set -eu

echo "create database lobby_db" | psql -h localhost -U postgres -d postgres
echo "create user lobby_user with password 'postgres'" | psql -h localhost -U postgres -d postgres
echo "alter database lobby_db owner to lobby_user" | psql -h localhost -U postgres -d postgres

./gradlew flywayMigrate
./gradlew :http-server:shadowJar

 # Http server output is suppressed by Travis when it is launched with gradle or when it is launched by the tests
 # themselves. Launching the server from jar file is a hack to work around this and allows server output to
 # be visible in travis logs.
readonly RELEASE_VERSION=$(sed 's/version\s*=\s*//' game-core/src/main/resources/META-INF/triplea/product.properties)
readonly HTTP_SERVER_JAR_PATH="http-server/build/libs/triplea-http-server-${RELEASE_VERSION}.jar server"
java -jar "$HTTP_SERVER_JAR_PATH" ./http-server/configuration-prerelease.yml &
