#!/bin/bash

## Installs the lobby using a build artifact passed as command line into a folder called "triplea_prerelease_lobby"

LOBBY_ARTIFACT=$1
INSTALL_DIR=triplea_prerelease_lobby

PID_FILE="$INSTALL_DIR/.prereleases_lobby_running.pid"
if [ -f $PID_FILE ]; then
  PID=$(cat $PID_FILE)
  if [ ! -z "$PID" ]; then
    kill $PID
    sleep 1
  fi
  rm $PID_FILE
fi

unzip -d $INSTALL_DIR $LOBBY_ARTIFACT
cd $INSTALL_DIR
nohup java -server  -Xmx192m -classpath bin/triplea.jar:lib/derby-10.10.1.1.jar -Dtriplea.lobby.port=33333 -Dtriplea.lobby.console=true games.strategy.engine.lobby.server.LobbyServer &

NEW_PID=$!
if [ ! -z $NEW_PID ]; then
  echo $NEW_PID > $PID_FILE
fi
rm $LOBBY_ARTIFACT
