#!/bin/bash

echo "Configure Git and PUSH A TAG - this trigger and execute the deploy section of this same build file, in the same travis linux container (skip_cleanup setting below is important)"
git config --global user.email "tripleabuilderbot@gmail.com"
git config --global user.name "tripleabuilderbot"
export TAGGED_VERSION="$BUILD_VERSION.$TRAVIS_BUILD_NUMBER"
git tag $TAGGED_VERSION -a -m "$TAGGED_VERSION"
git push -q https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/triplea-game/triplea --tags 2>&1 | sed 's|https://.*github|https://[secure]@github|'
