#!/bin/bash

## Note: The redirect to dev/nulls are to prevent the token from being printed in case there is a failure

## boiler plate git setup
git config --global user.email "tripleabuilderbot@gmail.com"
git config --global user.name "tripleabuilderbot"

## clone the website repo, suppress any output
git clone --quiet https://${PUSH_TO_WEBSITE_TOKEN}@github.com/triplea-game/triplea-game.github.io.git website 2>&1 > /dev/null

## copy in the new maps.yaml
cp ./triplea_maps.yaml ./website/_data/

## do git stuff, check if there is a diff, if so, commit and push it
cd website
UPDATED=1; git status | grep "nothing to commit" && UPDATED=0

if [ "$UPDATED" -eq 1 ]; then
  git commit _data/triplea_maps.yaml -m "Bot: update triplea_maps.yaml after game engine build $TAGGED_VERSION"
  git push -fq origin master 2>&1 > /dev/null 
fi

cd ..
rm -rf website
