#!/bin/bash

git clone https://github.com/triplea-game/triplea-game.github.io.git website
cp triplea_maps.yaml website/_data/
cd website

STATUS=0; git status | grep "nothing to commit" && STATUS=1

if [ "$STATUS" -eq 1 ]; then
  git commit _data/triplea_maps.yaml -m "Bot: update triplea_maps.yaml after game engine build $TAGGED_VERSION"
  ## sed is here on the next line in case there is a failure message, make sure we block out the github auth token
  ## so we don't have to rotate it.
  git push -q https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/triplea-game/triplea | sed 's|https://.*github|https://[secure]@github|'
fi

cd ..
