#!/bin/bash

if [ -z "$INSTALL4J_LICENSE" ]; then
 echo "Error: required license environment variable: INSTALL4J_LICENSE, was not set"
 exit -1
fi

export WINDOWS_32_JRE="windows-x86-1.8.0_66.tar.gz"
export WINDOWS_64_JRE="windows-amd64-1.8.0_66.tar.gz"
export MAC_JRE="macosx-amd64-1.8.0_66.tar.gz"
export ASSET_URL="http://github.com/triplea-game/assets/blob/master/install4j"
export JRE_HOME="$(cd ~; pwd)/install4j6/jres"

echo "Downloading and installing install4j"
wget -O install4j_unix.sh $ASSET_URL/install4j_unix_6_0_4.sh?raw=true
chmod +x install4j_unix.sh
./install4j_unix.sh -q

echo "Downloading JREs that will be bundled with installers"
wget -O $MAC_JRE $ASSET_URL/$MAC_JRE?raw=true
mv $MAC_JRE $JRE_HOME/

wget -O $WINDOWS_32_JRE $ASSET_URL/$WINDOWS_32_JRE?raw=true
mv $WINDOWS_32_JRE $JRE_HOME/

wget -O $WINDOWS_64_JRE $ASSET_URL/$WINDOWS_64_JRE?raw=true
mv $WINDOWS_64_JRE $JRE_HOME/


mkdir -p ~/.gradle

## Next, append install4jHomeDir property to ~/.gradle/gradle.properties, 
## iff the property is not already present in the file
## Detailed explanation of the commands:
## The grep simply does the check if the property is there, the echo then 
## does the append, the CD subshell gets us the absolute path to the home folder,
## and last this is appended to the gradle properties file
grep -q "install4jHomeDir" ~/.gradle/gradle.properties 2> /dev/null || echo "install4jHomeDir=$(cd ~ && pwd)/install4j6" >> ~/.gradle/gradle.properties

echo "Now Running Install4j to build OS specific installers"
~/install4j6/bin/install4jc -L $INSTALL4J_LICENSE

echo "Environment Now ready to execute 'gradle release'"
echo ""

