#!/bin/bash

if [ -z "$INSTALL4J_LICENSE" ]; then
 echo "Error: required license environment variable: INSTALL4J_LICENSE, was not set"
 exit -1
fi

export ASSET_URL="http://github.com/triplea-game/assets/blob/master/install4j"
mkdir -p ~/.install4j6/jres
export JRE_HOME="$(cd ~; pwd)/install4j6/jres"

echo "Downloading and installing install4j"
wget -O install4j_unix.sh $ASSET_URL/install4j_unix_6_0_4.sh?raw=true
chmod +x install4j_unix.sh
./install4j_unix.sh -q

mkdir -p ~/.gradle

## Next, append install4jHomeDir property to ~/.gradle/gradle.properties, 
## iff the property is not already present in the file
## Detailed explanation of the commands:
## The grep simply does the check if the property is there, the echo then 
## does the append, the CD subshell gets us the absolute path to the home folder,
## and last this is appended to the gradle properties file
grep -q "install4jHomeDir" ~/.gradle/gradle.properties 2> /dev/null || echo "install4jHomeDir=$(cd ~ && pwd)/install4j6" >> ~/.gradle/gradle.properties

echo "Now Running Install4j to build OS specific installers"
~/install4j6/bin/install4jc -L $INSTALL4J_LICENSE

echo "Environment Now ready to execute 'gradle release'"
echo ""

