#!/usr/bin/python3
import yaml
import sys

with open(sys.argv[1], 'r') as stream:
	try:
		for map in yaml.safe_load(stream):
			for key, value in map.items():
				if isinstance(value, str):
					map[key] = value.strip();
			map['slug'] = map['mapName'].lower().replace(' ', '-');
			with open(sys.argv[2] + map['slug'] + '.html', 'w+') as mapFile:
				mapFile.write('---\n');
				map['title'] = map['mapName'] + ' | TripleA Map';
				description = map.pop('description', '');
				map['dlurl'] = map.pop('url', '');
				yaml.dump(map, mapFile, default_flow_style=False);
				mapFile.write('---\n');
				mapFile.write(description);
				mapFile.write('\n');
	except yaml.YAMLError as exc:
		print(exc);
