/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

package games.strategy.triplea.Dynamix_AI.UI;

import games.strategy.triplea.Dynamix_AI.DSettings;

/**
 *
 * @author Stephen
 */
public class SettingsWindow extends javax.swing.JFrame {

    /** Creates new form SettingsWindow */
    public SettingsWindow()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        v_pausingPanel = new javax.swing.JPanel();
        v_actionLengthGoalRB = new javax.swing.JRadioButton();
        v_actionWaitGoalRB = new javax.swing.JRadioButton();
        v_totalLengthGoalsPanel = new javax.swing.JPanel();
        v_purchaseWait_AL = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        v_combatMoveWait_AL = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        v_nonCombatMoveWait_AL = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        v_placementWait_AL = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        v_actionWaitGoalsPanel = new javax.swing.JPanel();
        v_combatMoveWait_AW = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        v_purchaseWait_AW = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        v_nonCombatMoveWait_AW = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        v_placementWait_AW = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        v_okButton = new javax.swing.JButton();
        v_cancelButton = new javax.swing.JButton();
        v_restoreDefaultsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dynamix AI Settings");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        v_pausingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("AI Pausing"));
        v_pausingPanel.setName("v_pausingPanel"); // NOI18N

        buttonGroup1.add(v_actionLengthGoalRB);
        v_actionLengthGoalRB.setSelected(true);
        v_actionLengthGoalRB.setText("Action Length Goal");
        v_actionLengthGoalRB.setToolTipText("This causes the AI to pause just enough for the calculating and displaying of each action to equal the time alloted.");
        v_actionLengthGoalRB.setName("v_actionLengthGoalRB"); // NOI18N
        v_actionLengthGoalRB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                v_actionLengthGoalRBStateChanged(evt);
            }
        });

        buttonGroup1.add(v_actionWaitGoalRB);
        v_actionWaitGoalRB.setText("Action Wait Goal");
        v_actionWaitGoalRB.setToolTipText("This causes the AI to pause the alloted time after each action is calculated and displayed.");
        v_actionWaitGoalRB.setName("v_actionWaitGoalRB"); // NOI18N

        v_totalLengthGoalsPanel.setName("v_totalLengthGoalsPanel"); // NOI18N

        v_purchaseWait_AL.setModel(new javax.swing.SpinnerNumberModel(750, 0, 25000, 50));
        v_purchaseWait_AL.setName("v_purchaseWait_AL"); // NOI18N

        jLabel5.setText("Milliseconds");
        jLabel5.setName("jLabel5"); // NOI18N

        v_combatMoveWait_AL.setModel(new javax.swing.SpinnerNumberModel(750, 0, 25000, 50));
        v_combatMoveWait_AL.setName("v_combatMoveWait_AL"); // NOI18N

        jLabel6.setText("Milliseconds");
        jLabel6.setName("jLabel6"); // NOI18N

        v_nonCombatMoveWait_AL.setModel(new javax.swing.SpinnerNumberModel(750, 0, 25000, 50));
        v_nonCombatMoveWait_AL.setName("v_nonCombatMoveWait_AL"); // NOI18N

        jLabel7.setText("Milliseconds");
        jLabel7.setName("jLabel7"); // NOI18N

        v_placementWait_AL.setModel(new javax.swing.SpinnerNumberModel(750, 0, 25000, 50));
        v_placementWait_AL.setName("v_placementWait_AL"); // NOI18N

        jLabel8.setText("Milliseconds");
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout v_totalLengthGoalsPanelLayout = new javax.swing.GroupLayout(v_totalLengthGoalsPanel);
        v_totalLengthGoalsPanel.setLayout(v_totalLengthGoalsPanelLayout);
        v_totalLengthGoalsPanelLayout.setHorizontalGroup(
            v_totalLengthGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_totalLengthGoalsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(v_totalLengthGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(v_totalLengthGoalsPanelLayout.createSequentialGroup()
                        .addComponent(v_purchaseWait_AL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(v_totalLengthGoalsPanelLayout.createSequentialGroup()
                        .addComponent(v_combatMoveWait_AL, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(v_totalLengthGoalsPanelLayout.createSequentialGroup()
                        .addComponent(v_nonCombatMoveWait_AL, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(v_totalLengthGoalsPanelLayout.createSequentialGroup()
                        .addComponent(v_placementWait_AL, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        v_totalLengthGoalsPanelLayout.setVerticalGroup(
            v_totalLengthGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_totalLengthGoalsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(v_totalLengthGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_purchaseWait_AL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(v_totalLengthGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_combatMoveWait_AL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(v_totalLengthGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_nonCombatMoveWait_AL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(v_totalLengthGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_placementWait_AL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        v_actionWaitGoalsPanel.setName("v_actionWaitGoalsPanel"); // NOI18N

        v_combatMoveWait_AW.setModel(new javax.swing.SpinnerNumberModel(250, 0, 25000, 50));
        v_combatMoveWait_AW.setEnabled(false);
        v_combatMoveWait_AW.setName("v_combatMoveWait_AW"); // NOI18N
        v_combatMoveWait_AW.setNextFocusableComponent(v_nonCombatMoveWait_AW);

        jLabel9.setText("Milliseconds");
        jLabel9.setName("jLabel9"); // NOI18N

        v_purchaseWait_AW.setModel(new javax.swing.SpinnerNumberModel(250, 0, 25000, 50));
        v_purchaseWait_AW.setEnabled(false);
        v_purchaseWait_AW.setName("v_purchaseWait_AW"); // NOI18N
        v_purchaseWait_AW.setNextFocusableComponent(v_combatMoveWait_AW);

        jLabel10.setText("Milliseconds");
        jLabel10.setName("jLabel10"); // NOI18N

        v_nonCombatMoveWait_AW.setModel(new javax.swing.SpinnerNumberModel(250, 0, 25000, 50));
        v_nonCombatMoveWait_AW.setEnabled(false);
        v_nonCombatMoveWait_AW.setName("v_nonCombatMoveWait_AW"); // NOI18N

        jLabel11.setText("Milliseconds");
        jLabel11.setName("jLabel11"); // NOI18N

        v_placementWait_AW.setModel(new javax.swing.SpinnerNumberModel(250, 0, 25000, 50));
        v_placementWait_AW.setEnabled(false);
        v_placementWait_AW.setName("v_placementWait_AW"); // NOI18N

        jLabel12.setText("Milliseconds");
        jLabel12.setName("jLabel12"); // NOI18N

        javax.swing.GroupLayout v_actionWaitGoalsPanelLayout = new javax.swing.GroupLayout(v_actionWaitGoalsPanel);
        v_actionWaitGoalsPanel.setLayout(v_actionWaitGoalsPanelLayout);
        v_actionWaitGoalsPanelLayout.setHorizontalGroup(
            v_actionWaitGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_actionWaitGoalsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(v_actionWaitGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(v_actionWaitGoalsPanelLayout.createSequentialGroup()
                        .addComponent(v_purchaseWait_AW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(v_actionWaitGoalsPanelLayout.createSequentialGroup()
                        .addComponent(v_combatMoveWait_AW, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addGroup(v_actionWaitGoalsPanelLayout.createSequentialGroup()
                        .addComponent(v_nonCombatMoveWait_AW, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(v_actionWaitGoalsPanelLayout.createSequentialGroup()
                        .addComponent(v_placementWait_AW, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)))
                .addContainerGap())
        );
        v_actionWaitGoalsPanelLayout.setVerticalGroup(
            v_actionWaitGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_actionWaitGoalsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(v_actionWaitGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_purchaseWait_AW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(v_actionWaitGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_combatMoveWait_AW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(v_actionWaitGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_nonCombatMoveWait_AW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(v_actionWaitGoalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_placementWait_AW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setText("Purchase Phase:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Combat Move Phase:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Non Combat Move Phase:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Placement Phase:");
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout v_pausingPanelLayout = new javax.swing.GroupLayout(v_pausingPanel);
        v_pausingPanel.setLayout(v_pausingPanelLayout);
        v_pausingPanelLayout.setHorizontalGroup(
            v_pausingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_pausingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(v_pausingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_pausingPanelLayout.createSequentialGroup()
                        .addComponent(v_actionLengthGoalRB)
                        .addGap(51, 51, 51)
                        .addComponent(v_actionWaitGoalRB)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_pausingPanelLayout.createSequentialGroup()
                        .addGroup(v_pausingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(v_totalLengthGoalsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v_actionWaitGoalsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        v_pausingPanelLayout.setVerticalGroup(
            v_pausingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_pausingPanelLayout.createSequentialGroup()
                .addGroup(v_pausingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_actionWaitGoalRB)
                    .addComponent(v_actionLengthGoalRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(v_pausingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v_actionWaitGoalsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v_totalLengthGoalsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(v_pausingPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4))
        );

        jPanel3.setName("jPanel3"); // NOI18N

        v_okButton.setText("OK");
        v_okButton.setName("v_okButton"); // NOI18N
        v_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_okButtonActionPerformed(evt);
            }
        });

        v_cancelButton.setText("Cancel");
        v_cancelButton.setName("v_cancelButton"); // NOI18N
        v_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_cancelButtonActionPerformed(evt);
            }
        });

        v_restoreDefaultsButton.setText("Restore Defaults");
        v_restoreDefaultsButton.setName("v_restoreDefaultsButton"); // NOI18N
        v_restoreDefaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_restoreDefaultsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v_restoreDefaultsButton)
                .addGap(99, 99, 99)
                .addComponent(v_okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v_cancelButton)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v_cancelButton)
                    .addComponent(v_restoreDefaultsButton)
                    .addComponent(v_okButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v_pausingPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v_pausingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-609)/2, (screenSize.height-311)/2, 609, 311);
    }// </editor-fold>//GEN-END:initComponents

    private void v_actionLengthGoalRBStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_v_actionLengthGoalRBStateChanged
    {//GEN-HEADEREND:event_v_actionLengthGoalRBStateChanged
        ChangeTotalLengthPanelsState(v_actionLengthGoalRB.isSelected());
        ChangeActionWaitPanelsState(!v_actionLengthGoalRB.isSelected());
    }//GEN-LAST:event_v_actionLengthGoalRBStateChanged

    private void v_restoreDefaultsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_v_restoreDefaultsButtonActionPerformed
    {//GEN-HEADEREND:event_v_restoreDefaultsButtonActionPerformed
        v_actionLengthGoalRB.setSelected(false); //Also triggers change of enabled state of panels

        v_purchaseWait_AL.setValue(750);
        v_combatMoveWait_AL.setValue(750);
        v_nonCombatMoveWait_AL.setValue(750);
        v_placementWait_AL.setValue(750);

        v_purchaseWait_AW.setValue(250);
        v_combatMoveWait_AW.setValue(250);
        v_nonCombatMoveWait_AW.setValue(250);
        v_placementWait_AW.setValue(250);
    }//GEN-LAST:event_v_restoreDefaultsButtonActionPerformed

    private void v_okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_v_okButtonActionPerformed
    {//GEN-HEADEREND:event_v_okButtonActionPerformed
        DSettings settings = new DSettings();
        settings.UseActionLengthGoals = v_actionLengthGoalRB.isSelected();

        settings.PurchaseWait_AL = Integer.parseInt(v_purchaseWait_AL.getValue().toString());
        settings.CombatMoveWait_AL = Integer.parseInt(v_combatMoveWait_AL.getValue().toString());
        settings.NonCombatMoveWait_AL = Integer.parseInt(v_nonCombatMoveWait_AL.getValue().toString());
        settings.PlacementWait_AL = Integer.parseInt(v_placementWait_AL.getValue().toString());

        settings.PurchaseWait_AW = Integer.parseInt(v_purchaseWait_AW.getValue().toString());
        settings.CombatMoveWait_AW = Integer.parseInt(v_combatMoveWait_AW.getValue().toString());
        settings.NonCombatMoveWait_AW = Integer.parseInt(v_nonCombatMoveWait_AW.getValue().toString());
        settings.PlacementWait_AW = Integer.parseInt(v_placementWait_AW.getValue().toString());

        DSettings.SaveSettings(settings);

        this.dispose();
    }//GEN-LAST:event_v_okButtonActionPerformed

    private void v_cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_v_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_v_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_v_cancelButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        DSettings settings = DSettings.LoadSettings();

        v_actionLengthGoalRB.setSelected(settings.UseActionLengthGoals); //Also triggers change of enabled state of panels

        v_purchaseWait_AL.setValue(settings.PurchaseWait_AL);
        v_combatMoveWait_AL.setValue(settings.CombatMoveWait_AL);
        v_nonCombatMoveWait_AL.setValue(settings.NonCombatMoveWait_AL);
        v_placementWait_AL.setValue(settings.PlacementWait_AL);

        v_purchaseWait_AW.setValue(settings.PurchaseWait_AW);
        v_combatMoveWait_AW.setValue(settings.CombatMoveWait_AW);
        v_nonCombatMoveWait_AW.setValue(settings.NonCombatMoveWait_AW);
        v_placementWait_AW.setValue(settings.PlacementWait_AW);
    }//GEN-LAST:event_formWindowOpened

    private void ChangeTotalLengthPanelsState(boolean enabled)
    {
        v_totalLengthGoalsPanel.setEnabled(enabled);
        v_purchaseWait_AL.setEnabled(enabled);
        v_combatMoveWait_AL.setEnabled(enabled);
        v_nonCombatMoveWait_AL.setEnabled(enabled);
        v_placementWait_AL.setEnabled(enabled);
    }
    private void ChangeActionWaitPanelsState(boolean enabled)
    {
        v_actionWaitGoalsPanel.setEnabled(enabled);
        v_purchaseWait_AW.setEnabled(enabled);
        v_combatMoveWait_AW.setEnabled(enabled);
        v_nonCombatMoveWait_AW.setEnabled(enabled);
        v_placementWait_AW.setEnabled(enabled);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton v_actionLengthGoalRB;
    private javax.swing.JRadioButton v_actionWaitGoalRB;
    private javax.swing.JPanel v_actionWaitGoalsPanel;
    private javax.swing.JButton v_cancelButton;
    private javax.swing.JSpinner v_combatMoveWait_AL;
    private javax.swing.JSpinner v_combatMoveWait_AW;
    private javax.swing.JSpinner v_nonCombatMoveWait_AL;
    private javax.swing.JSpinner v_nonCombatMoveWait_AW;
    private javax.swing.JButton v_okButton;
    private javax.swing.JPanel v_pausingPanel;
    private javax.swing.JSpinner v_placementWait_AL;
    private javax.swing.JSpinner v_placementWait_AW;
    private javax.swing.JSpinner v_purchaseWait_AL;
    private javax.swing.JSpinner v_purchaseWait_AW;
    private javax.swing.JButton v_restoreDefaultsButton;
    private javax.swing.JPanel v_totalLengthGoalsPanel;
    // End of variables declaration//GEN-END:variables

}
