#!/bin/bash

set -u

script_dir=$(dirname "$0")

green="\e[92m"
blue="\e[34m"
normal="\e[0m"
bold="\e[1m"
boldRed="${bold}\e[91m"

javaFiles=$(mktemp)
testFiles=$(mktemp)
sqlFiles=$(mktemp)
trap 'rm $javaFiles $sqlFiles' EXIT


## Create a cache of java and SQL files for faster iteration over all files.

find . -type f -name "*.java" > "$javaFiles"
find . -type f -name "*Test.java" > "$testFiles"
find spitfire-server/database/src/main/resources -type f -name "*.sql" > "$sqlFiles"

status=0


function main() {
  favorJava9CollectionsApi
  #referToCollectionsByInterfaceType
  removeUnusedLogAnnotations
  #preferSlf4jOverJavaLogging
  noTabsInSql
  useEmptyOverSizeEqualsZero
  useStaticImportsInTest
  useIsEmptyMatcherOverHasSizeZero
  useJavaxNonnullInsteadOfLombokNonNull
}

function title() {
  echo -e "${bold}${blue}$1${normal}"
}

function example() {
  echo -e "${blue}Ex: $1${normal}"
}

function displayResult() {
  local found="$1"
  if [ "$found" -eq 0 ]; then
    echo -e "${green}[OK]${normal}"
  else
    echo -e "${boldRed}[FIX]${normal}"
  fi
  echo ""
  
}

function favorJava9CollectionsApi() {
  title "Verifying preference to use List.of(), Map.of() and Set.of() compared to java.util.Collections.*"
  example "instead of 'Collections.singleton(value)', use 'Set.of(value)'"
  local found=0

  while read -r file; do
    grep --color=auto -Hn -f "$script_dir/style.include/disallowed-collection-calls" "$file" && status=1 && found=1
    grep --color=auto -Hn -f "$script_dir/style.include/disallowed-collection-imports" "$file" && status=1 && found=1
  done <<< "$(cat "$javaFiles")"

  displayResult "$found"
}

function referToCollectionsByInterfaceType() {
  title "Assign to collection types using their interface"
  example "instead of 'ArrayList<String> list =', use 'List<String> list = '"
  local found=0

  while read -r file; do
    grep --color=auto -EHn -f "$script_dir/style.include/concrete-collection-types" "$file" && status=1 && found=1
  done <<< "$(cat "$javaFiles")"
  
  displayResult "$found"
}

function removeUnusedLogAnnotations() {
  title "Remove unused lombok @Slf4j annotations"
  local found=0

  while read -r file; do
    if grep -Eq "@Slf4j" "$file"; then
      if ! grep -Eq "log::|log\." "$file"; then
        echo -e "${bold}$file${normal}"
        found=1
        status=1
      fi
    fi
  done <<< "$(cat "$javaFiles")"

  displayResult "$found"
}

function preferSlf4jOverJavaLogging() {
  title "Use @Slf4j instead of @Log"
  local found=0

  while read -r file; do
    if grep --color=auto -EHn "@Log|^import java.util.log" "$file"; then
      found=1
      status=1
    fi
  done <<< "$(cat "$javaFiles")"

  displayResult "$found"
}

function noTabsInSql() {
  title "Use spaces in SQL and not tabs"
  local found=0
  while read -r file; do
    grep --color=auto -Pn "\t" "$file" && status=1 && found=1
  done <<< "$(cat "$sqlFiles")"
  displayResult "$found"
}

function useEmptyOverSizeEqualsZero() {
  title "Avoid using size() to check for empty or not empty"
  example "size() == 0 -> isEmpty(), size() > 0 -> !isEmpty()"
  local found=0
  while read -r file; do
    grep --color=auto -EHn \
        "size\(\) == 0|size\(\) < 1|size\(\) <= 0|size\(\) > 0|size\(\) != 0|size\(\) >= 1" "$file" \
      && status=1 && found=1
  done <<< "$(cat "$javaFiles")"

  displayResult "$found"
}


# Checks for static imports by looking for fully qualified constructs used in test, eg:
#   Mockito.when
# We distinguish from imports and standard usages by looking for a trailing semicolon, eg:
#   import static ..MatcherAssert.assertThat;
# If we do not see that trailing semi-colon, then we have found something that is not statically
# imported.
function useStaticImportsInTest() {
  title "Use static imports in test"
  example "Mockito.when(..) -> when(..)"
  local found=0
  while read -r file; do
    grep --color=auto -EHn \
      "Mockito.when[^;]|Mockito.verify[^;|NoMoreInteractions;]|MatcherAssert.assertThat[^;]|Is\.is[^;]|IsInstanceOf\.instanceOf[^;]" \
      "$file" \
     && status=1 && found=1
  done <<< "$(cat "$testFiles")"

  displayResult "$found"
}

function useIsEmptyMatcherOverHasSizeZero() {
  title "Use IsEmptyCollection.isEmpty() instead of hasSize(0)"
  example "assertThat(collection, hasSize(0)) -> assertThat(collection, is(empty())"
  local found=0
  while read -r file; do
    grep --color=auto -Hn \
      "hasSize(0)" \
      "$file" \
     && status=1 && found=1
  done <<< "$(cat "$testFiles")"
  
  displayResult "$found"
}

function useJavaxNonnullInsteadOfLombokNonNull() {
  title "Use javax.annotation.Nonnull instead of lombok.NonNull"
  local found=0
  while read -r file; do
    grep --color=auto --with-filename --line-number \
      "lombok.NonNull" \
      "$file" \
     && status=1 && found=1
  done <<< "$(cat "$javaFiles")"

  displayResult "$found"
}

main

exit "$status"
