- name: apt install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: generate dhparam.pem
  become: true
  shell:
    cmd: openssl dhparam -out /etc/nginx/dhparam.pem 4096
    creates: /etc/nginx/dhparam.pem

- name: set permissions of dhparam.pem
  become: true
  file:
    dest: /etc/nginx/dhparam.pem
    mode: 600

- name: create SSL keys if needed
  become: true
  command: openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout {{ nginx_ssl_certificate_key }} -out {{ nginx_ssl_certificate }} -batch -subj '/CN=localhost' -sha256
  args:
    creates: "{{ nginx_ssl_certificate_key }}"

- name: deploy nginx sites_enabled configuation
  become: true
  template:
    src: etc_nginx_sites_enabled_default.j2
    dest: /etc/nginx/sites-enabled/default

- name: allow ports
  become: true
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ nginx_allowed_ports }}"

- name: relaunch nginx
  become: true
  systemd:
    name: nginx
    state: restarted

