- name: apt install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: generate dhparam.pem
  become: true
  shell:
    cmd: openssl dhparam -out {{ nginx_ssl_dhparams }} 4096
    creates: "{{ nginx_ssl_dhparams }}"

- name: set permissions of dhparam.pem
  become: true
  file:
    dest: "{{ nginx_ssl_dhparams }}"
    mode: 600

- name: check for nginx cert key
  stat:
    path: "{{ nginx_ssl_certificate_key }}"
  register: cert_key
  changed_when: false

- name: check for nginx certificate
  stat:
    path: "{{ nginx_ssl_certificate }}"
  register: cert
  changed_when: false

- name: create SSL keys if needed
  become: true
  when: (cert_key.stat.exists == false) or (cert.stat.exists == false)
  command: openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout {{ nginx_ssl_certificate_key }} -out {{ nginx_ssl_certificate }} -batch -subj '/CN=localhost' -sha256 -addext "subjectAltName = IP:127.0.0.1, IP:::1"

- name: deploy nginx sites_enabled configuation
  become: true
  template:
    src: etc_nginx_sites_enabled_default.j2
    dest: /etc/nginx/sites-enabled/default

- name: allow ports
  become: true
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ nginx_allowed_ports }}"

- name: relaunch nginx
  become: true
  systemd:
    name: nginx
    state: restarted

