package games.strategy.triplea.settings;

public enum PreferenceKey {
  MAP_EDGE_SCROLL_ZONE_SIZE,
  MAP_EDGE_FASTER_SCROLL_ZONE_SIZE,
  MAP_EDGE_FASTER_SCROLL_MULTIPLER,
  FASTER_ARROW_KEY_SCROLL_MULTIPLIER,
  WHEEL_SCROLL_AMOUNT,
  MAP_EDGE_SCROLL_SPEED,
  USER_MAPS_FOLDER_PATH, SAVE_GAMES_FOLDER_PATH, ARROW_KEY_SCROLL_SPEED
}
