package games.strategy.triplea.settings;

public enum PreferenceKey {
  MAP_EDGE_SCROLL_ZONE_SIZE,
  MAP_EDGE_FASTER_SCROLL_ZONE_SIZE,
  MAP_EDGE_FASTER_SCROLL_MULTIPLER,
  FASTER_ARROW_KEY_SCROLL_MULTIPLIER,
  WHEEL_SCROLL_AMOUNT,
  MAP_EDGE_SCROLL_SPEED,
  USER_MAPS_FOLDER_PATH,
  SAVE_GAMES_FOLDER_PATH,
  AI_PAUSE_DURACTION,
  BATTLE_CALC_SIMULATION_COUNT_DICE,
  BATTLE_CALC_SIMULATION_COUNT_LOW_LUCK,
  CONFIRM_ENEMY_CASUALTIES, ARROW_KEY_SCROLL_SPEED
}
