package games.strategy.triplea.settings;


/**
 * Settings 'keys' used to look up user settings from system preferences.
 */
public enum SystemPreferenceKey {
  MAP_EDGE_SCROLL_ZONE_SIZE, MAP_EDGE_FASTER_SCROLL_ZONE_SIZE, MAP_EDGE_FASTER_SCROLL_MULTIPLER, FASTER_ARROW_KEY_SCROLL_MULTIPLIER, WHEEL_SCROLL_AMOUNT, MAP_EDGE_SCROLL_SPEED, USER_MAPS_FOLDER_PATH, SAVE_GAMES_FOLDER_PATH, AI_PAUSE_DURACTION, BATTLE_CALC_SIMULATION_COUNT_DICE, BATTLE_CALC_SIMULATION_COUNT_LOW_LUCK, CONFIRM_ENEMY_CASUALTIES, CONFIRM_DEFENSIVE_ROLLS, FOCUS_ON_OWN_CASUALTIES, SHOW_BATTLES_BETWEEN_AI, MAP_FOLDER_OVERRIDE, BATTLE_DICE_PER_ROW, ARROW_KEY_SCROLL_SPEED
}
