version: '3'
services:
  database:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "127.0.0.1:5432:5432"
  nginx:
    image: nginx:stable-alpine-perl
    ports:
      - "127.0.0.1:80:80"
