- name: create service user
  become: true
  user:
    name: "{{ http_server_user }}"
    create_home: yes
    system: yes

- name: deploy jar file
  become: true
  copy:
    src: "{{ http_server_jar }}"
    dest: "{{ http_server_home_folder }}/{{ http_server_jar }}"
    owner: "{{ http_server_user }}"
    group: "{{ http_server_user }}"

- name: deploy run_server script
  become: true
  template:
    src: run_server.j2
    dest: "{{ http_server_run_file }}"
    mode: "755"
    owner: "{{ http_server_user }}"
    group: "{{ http_server_user }}"

- name: deploy server config file
  become: true
  template:
    src: configuration.yml.j2
    dest: "{{ http_server_home_folder}}/configuration.yml"
    mode: "644"
    owner: "{{ http_server_user }}"
    group: "{{ http_server_user }}"

- name: install systemd service script
  become: true
  template:
    src: http_server.service.j2
    dest: /lib/systemd/system/http_server.service
    mode: "644"

- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: enable and start service
  become: true
  service:
    name: http_server
    state: started
    enabled: yes
