#!/bin/bash

# This script is used to execute prereleae and production deployments.
# It should be run from the infrastructure machine.
# The script is saved in git repository so that we can track changes to it.
# If the script is updated, upload a new copy to the infrastructure machine
# to /home/ansible.


VERSION=${1-}
INVENTORY_FILE=${2-}

function usage() {
  echo "Usage: $0 [Version] [InventoryFile]"
  echo "  Version: The version of tripleA to be downloaded and installed, eg: 1.10.0.141"
  echo "  InventoryFile: The inventory file to run, one of: {production|prerelease}"
  echo "Example: $0 1.10.5252 prerelease"
  exit 1
}

if [ -e "$VERSION" ] || [ -e "$INVENTORY_FILE" ]; then
  usage
fi
export VERSION=$VERSION

if [ "$INVENTORY_FILE" != production ] && [ "$INVENTORY_FILE" != prerelease ]; then
  usage
fi

VAULT_PASSWORD_FILE="vault_password"
if [ ! -f "$VAULT_PASSWORD_FILE" ]; then
  echo "Error: $VAULT_PASSWORD_FILE must exist"
  exit 1
fi

if [ ! -f "ansible_ssh_key.ed25519" ]; then
  echo "Could not find file ansible_ssh_key.ed25519 at current directory"
  exit 1
fi

ansible-vault view --vault-password-file="$VAULT_PASSWORD_FILE" ansible_ssh_key.ed25519 | ssh-add -


function main() {
  downloadHttpServerJar

  downloadBotJar

  downloadMigrations

  ansible-playbook -D -v \
      --vault-password-file "$VAULT_PASSWORD_FILE" \
     ansible/site.yml \
     -i "ansible/inventory/$INVENTORY_FILE"
}

function downloadHttpServerJar() {
  HTTP_SERVER_ZIP="triplea-http-server-$VERSION.zip"
  rm -f $HTTP_SERVER_ZIP
  HTTP_SERVER_DL_LOCATION="https://github.com/triplea-game/triplea/releases/download/$VERSION/$HTTP_SERVER_ZIP"
  wget $HTTP_SERVER_DL_LOCATION
  if [ ! -f "$HTTP_SERVER_ZIP" ]; then
    echo "ERROR: failed to download http server zip from: $HTTP_SERVER_ZIP"
    exit 1
  fi

  rm -rf lobby/
  unzip $HTTP_SERVER_ZIP -d http-server
  rm $HTTP_SERVER_ZIP

  mkdir -p ansible/roles/http_server/files/
  mv http-server/configuration-prerelease.yml \
     http-server/configuration-production.yml \
     http-server/bin/triplea-http-server-$VERSION.jar \
       ansible/roles/http_server/files/
}

function downloadBotJar() {
  BOT_ZIP="triplea-game-headless-$VERSION.zip"
  rm -f $BOT_ZIP
  BOT_DL_LOCATION="https://github.com/triplea-game/triplea/releases/download/$VERSION/$BOT_ZIP"
  wget $BOT_DL_LOCATION
  if [ ! -f "$BOT_ZIP" ]; then
    echo "ERROR: failed to download bot zip from: $BOT_DL_LOCATION"
  fi
  rm -rf bot/
  unzip $BOT_ZIP -d bot
  rm $BOT_ZIP
  mkdir -p ansible/roles/bot/files/
  mv bot/bin/triplea-game-headless-$VERSION.jar ansible/roles/bot/files/
}


function downloadMigrations() {
  local migrationsZip="migrations.zip"
  rm -f $migrationsZip
  local migrationsDlLocation="https://github.com/triplea-game/triplea/releases/download/$VERSION/migrations.zip"
  wget $migrationsDlLocation
  if [ ! -f "$migrationsZip" ]; then
    echo "ERROR: failed to download migrations zip from: $migrationsDlLocation"
  fi
  
  rm $BOT_ZIP
  mkdir -p ansible/roles/flyway/files/
  mv $migrationsZip ansible/roles/flyway/files/
}

main
