#!/bin/bash
set -x

source infrastructure-machine/secrets

CUR_FOLDER=$(basename $(pwd))
if [ "$CUR_FOLDER" != infrastructure ]; then
  echo "Error, must be in the infrastructure folder to run this script."
  exit 1
fi

export VERSION=$(sed 's/.*=\s*//' ../game-core/src/main/resources/META-INF/triplea/product.properties)
echo "Parsed version number: $VERSION"

function buildLobbyJar() {
  # check if a lobby jar is built, if not build it and copy to location where ansible can find it.
  local jarFile=triplea-lobby-$VERSION.jar
  local targetFolder=./ansible/roles/lobby/files
  if [ ! -e $targetFolder/$jarFile ]; then
     (
       cd ../
       if [ ! -e lobby/build/libs/$jarFile ]; then
         ./gradlew shadowjar
       fi
       cd infrastructure
       mkdir -p $targetFolder
       cp lobby/build/libs/$jarFile $targetFolder
     ) 
  fi
}

buildLobbyJar

function buildBotJar() {
  local jarFile=triplea-game-headless-$VERSION.jar
  local targetFolder=./ansible/roles/bot/files/
  # check if a bot jar is built, if not build it and copy to location where ansible can find it.
  if [ ! -e $targetFolder/$jarFile ]; then
     (
       cd ../
       if [ ! -e lobby/build/libs/$jarFile ]; then
         ./gradlew shadowjar
       fi
       cd infrastructure
       mkdir -p $targetFolder
       cp ../game-headless/build/libs/$jarFile $targetFolder
     ) 
  fi
}

buildBotJar

function buildMigrations() {
  local targetFolder=./ansible/roles/flyway/files/
  local zipFile=migrations.zip
  if [ ! -e $targetFolder/$zipFile ]; then
    (
      cd ../lobby-db
      if [ ! -e build/distributions/$zipFile ]; then
        ../gradlew release 
      fi
      cd ../infrastructure
      mkdir -p $targetFoldee
      cp ../lobby-db/build/distributions/$zipFile $targetFolder
    )
  fi
}

buildMigrations

ansible-playbook -D -v \
    "$@" \
    ansible/site.yml \
    -i ansible/inventory/vagrant 
