Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "vagrantHost" do |vagrantHost|
    vagrantHost.vm.network "forwarded_port", guest: 22, host: 2010, host_ip: "127.0.0.1", id: "ssh"
    vagrantHost.vm.network "forwarded_port", guest: 3304, host: 3304, host_ip: "127.0.0.1"
    vagrantHost.vm.network "forwarded_port", guest: 443, host: 4430, host_ip: "127.0.0.1"
  end
end

