#!/bin/bash

set -e

scriptDir=$(dirname "$0")

export PGPASSWORD=postgres
if ! echo 'select 1' \
       | psql -h localhost -U postgres 2> /dev/null \
       | grep -q '1 row'; then
  echo "Starting docker database on localhost"
  "$scriptDir/../database/start_docker_db"
fi

"$scriptDir/.build/setup-database"
"$scriptDir/../../gradlew" :spitfire-server:dropwizard-server:check
"$scriptDir/../run/.build/find-unused-dbunit-datasets"
"$scriptDir/../../.build/code-convention-checks/check-custom-style" spitfire-server
