- name: install software properties common
  when: use_certbot
  apt:
    state: present
    name: software-properties-common

- name: install certbot and python for certbot on nginx
  when: use_certbot
  apt:
    state: present
    name:
      - certbot
      - python3-certbot-nginx

- name: run certbot to get certs
  when: use_certbot
  shell:
    cmd: |
       certbot certonly \
         --nginx -n \
         -m tripleabuilderbot@gmail.com \
         -d {{ inventory_hostname }} \
         --agree-tos \
         --rsa-key-size 4096
    creates: /etc/letsencrypt/live/{{ inventory_hostname }}/cert.pem
