@startuml
'https://plantuml.com/use-case-diagram

left to right direction
skinparam packageStyle rect
(UnitChooser)

(BattleDisplay) --> (UnitChooser)
(TripleAPlayer.pickTerritoryAndUnits) --> (UnitChooser)
(Place) --> (UnitChooser)
(TripleAFrame.scrambleUnitsQuery)--> (UnitChooser)
(TripleAFrame.selectUnitsQuery)--> (UnitChooser)
(TripleAFrame.moveFightersToCarrier)--> (UnitChooser)
(BattlePanel.getCasualtiesAa)--> (UnitChooser)
(EditPanel.selectUnitsToRemove)--> (UnitChooser)
(EditPanel.actionPerformed)--> (UnitChooser)
(MovePanel.selectUnitsToMove)--> (UnitChooser)
@enduml