name: Spotless Formatting
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run SpotlessApply to Auto-Fix
      run: ./gradlew --parallel spotlessApply
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: tripleabuilderbot
        author_email: tripleabuilderbot@gmail.com
        message: "Auto-Formatting"
        add: "*.java"
        force: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Spotless Check to Ensure Formatting Issues are Fixed
      run: ./gradlew spotlessCheck
