name: Auto Close GitHub Issues
on:
  issues:
    types: [opened]
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./triplea
        run: npm install

      - name: Run script closeIssues.js
        run: node scripts/closeIssues.js
        working-directory: ./triplea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
