name: Auto Close GitHub Issues
on:
  issues:
    types: [opened]
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
          
      - name: Debug working directory
        run: ls -la
        working-directory: ./scripts
        
      - name: Install dependencies
        run: npm install
        working-directory: ./scripts

      - name: Run script closeIssues.js
        run: node closeIssues.js
        working-directory: ./scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
