# Runs when master branch is updated.
# Creates & pushes a docker container for bots.

name: Master Branch Build - Build Bot Docker Container
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    env:
      IS_MASTER_BUILD: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Login to GitHub Container Registry
        if: ${{ env.IS_MASTER_BUILD }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build headless docker container
        if: ${{ env.IS_MASTER_BUILD }}
        run: |
          ./gradlew :game-app:game-headless:shadowJar
          docker build game-app/game-headless --tag ghcr.io/triplea-game/bot:latest
          docker push ghcr.io/triplea-game/bot:latest
