name: Check Links are Valid
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Links are Valid
      run: ./.travis/stages/verify/check-links-and-yaml-syntax/check-links

