name: Code Convention Checks
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Code Convention Checks
        run: ./.travis/stages/verify/code-convention-checks/run

