name: Deploy Prerelease
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Deploy to Prerelease
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set build version variables
        run: |
          echo "product_version=$BUILD_NUMBER" | tee -a $GITHUB_ENV
      - name: Deploy to Prerelease
        run: |
          eval "$(ssh-agent -s)"
          cd infrastructure
          echo "$ANSIBLE_VAULT_PASSWORD" > vault_password
          .build/set-build-number ${{ github.run_number }}
          ./run_ansible --deploy-type minimal --environment prerelease
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

