name: Master Branch Release
on: pull_request
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Master Branch Release Actions
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Load SSH private key into ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      - name: set build version variables
        run: |
          BUILD_NUMBER=$(.build/set-game-headed-build-number)
          echo "product_version=$BUILD_NUMBER"  >> $GITHUB_ENV
          echo "release_name=$(date +%Y-%B-%d) - $BUILD_NUMBER" >> $GITHUB_ENV
          
      - name: Create Github Release
        run: |
          echo "product_version = $product_version"
