# Jar file is useful for server code, so that the server code can depend on
# the TripleA client code (jar file). The TripleA client should include
# the 'http client' (AKA REST API) code for communicating with server
name: Publish Jar File
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#        with:
#          # Fetch depth of 0 is needed so we checkout the full revision history
#          # The current revision count will be used as our build-number
#          fetch-depth: '0'
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: set build version variables
        run: |
          BUILD_VERSION=$(game-app/run/.build/get-build-version)
          echo "JAR_VERSION=$BUILD_VERSION" | tee -a $GITHUB_ENV
      - name: Publish package
        run: ./gradlew :game-app:game-headed:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
