name: Auto-Formatting

on:
  pull_request:
    types: opened
    jobs:
      rebase:
        - uses: actions/checkout@master
        - name: Automatic Rebase
          uses: cirrus-actions/rebase@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run unit tests
      run: ./gradlew --parallel test
    - name: send coverage report to codecov
      uses: actions/code-cov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

