# Jar files uploaded are used as a maven dependency by server (eg: lobby)
name: Create Http JAR files and upload to github packages
on:
  push:
    branches:
      - main
    paths:
      - 'http-clients/lobby-client-data/**'
      - '.github/workflows/upload-http-client-jars.yml'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Fetch depth of 0 is needed so we checkout the full revision history
          # The current revision count will be used as our build-number
          fetch-depth: '0'
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: set build version variables
        run: |
          BUILD_VERSION=$(game-app/run/.build/get-build-version)
          echo "JAR_VERSION=$BUILD_VERSION" | tee -a $GITHUB_ENV
      - name: Publish lobby client JAR
        run: ./gradlew :lobby-client-data:publish --rerun-tasks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
